vtk_module(vtkFiltersGeneral
  GROUPS
    StandAlone
  DEPENDS
    #vtkCommonComputationalGeometry
    vtkFiltersCore
  TEST_DEPENDS
    vtkIOLegacy
    vtkIOXML
    vtkInteractionStyle
    vtkRenderingOpenGL
    vtkRenderingFreeType
    vtkRenderingAnnotation
    vtkTestingRendering
  KIT
    vtkFilters
  )
