/*=========================================================================

  Program:   Visualization Toolkit
  Module:    vtkPVDefaultModules.h
  Language:  C++
  Date:      $Date$
  Version:   $Revision$


Copyright (c) 1993-2001 Ken Martin, Will Schroeder, Bill Lorensen 
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

 * Neither name of Ken Martin, Will Schroeder, or Bill Lorensen nor the names
   of any contributors may be used to endorse or promote products derived
   from this software without specific prior written permission.

 * Modified source versions must be plainly marked as such, and must not be
   misrepresented as being the original software.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS ``AS IS''
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHORS OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

=========================================================================*/
// .NAME 
// .SECTION Description

#ifndef __vtkPVDefaultModules_h
#define __vtkPVDefaultModules_h

#include "vtkToolkits.h"

// Define the standard reader interfaces.
const char* vtkPVWindow::StandardReaderInterfaces =
"<ModuleInterfaces>\n"
"  <Module name=\"pvtkfile\" class=\"vtkPVDataSetReaderModule\" root_name=\"pvtkfile\"\n"
"          output=\"vtkDataSet\" module_type=\"Reader\"\n"
"          extensions=\".pvtk\" file_description=\"Parallel VTK Files\">\n"
"    <Source type=\"vtkPDataSetReader\"/>\n"
"  </Module>\n"
"  <Module name=\"vtkfile\" class=\"vtkPVDataSetReaderModule\" root_name=\"vtkfile\" \n"
"          output=\"vtkDataSet\" module_type=\"Reader\"\n"
"          extensions=\".vtk\" file_description=\"VTK Files\">\n"
"    <Source type=\"vtkPDataSetReader\"/>\n"
"  </Module>\n"
"  <Module name=\"stlreader\" class=\"vtkPVReaderModule\" root_name=\"stl\" \n"
"          output=\"vtkPolyData\" module_type=\"Reader\"\n"
"          extensions=\".stl\" file_description=\"Stereo Lithography\">\n"
"    <Source type=\"vtkSTLReader\"/>\n"
"  </Module>\n"
"  <Module name=\"popreader\" class=\"vtkPVAdvancedReaderModule\" \n"
"          root_name=\"pop\" output=\"vtkStructuredGrid\"\n"
"          module_type=\"Reader\"\n"
"          extensions=\".pop\" file_description=\"POP Ocean Files\">\n"
"    <Source type=\"vtkPOPReader\"/>\n"
"    <VectorEntry variable=\"Radius\" type=\"float\" \n"
"                 help=\"Set the radius of the data set\"/>\n"
"    <VectorEntry variable=\"ClipExtent\" type=\"int\" length=\"6\" \n"
"                 help=\"For reading a smaller extent.\"/>\n"
"    <VectorEntry variable=\"NumberOfGhostLevels\" type=\"int\" \n"
"                 help=\"Set the number of ghost levels to read.\"/>\n"
"  </Module>\n"
"  <Module name=\"ensight\" class=\"vtkPVEnSightReaderModule\" root_name=\"ensight\" \n"
"          output=\"vtkDataSet\" module_type=\"Reader\"\n"
"          extensions=\".case .sos\" file_description=\"EnSight Files\">\n"
"    <Source type=\"vtkGenericEnSightReader\"/>\n"
"  </Module>\n"
"</ModuleInterfaces>\n";

// Define the standard source interfaces.
const char* vtkPVWindow::StandardSourceInterfaces =
"<ModuleInterfaces>\n"
"\n"
"<Module name=\"ArrowSource\" root_name=\"Arrow\" output=\"vtkPolyData\" module_type=\"Source\">\n"
"  <Source type=\"vtkArrowSource\"/>\n"
"  <VectorEntry variable=\"TipResolution\" type=\"int\" help=\"Set the number of faces on the tip.\"/>\n"
"  <VectorEntry variable=\"TipRadius\" type=\"float\" help=\"Set the radius of the widest part of the tip.\"/>\n"
"  <VectorEntry variable=\"TipLength\" type=\"float\" help=\"Set the length of the tip (the whole arrow is length 1)\"/>\n"
"  <VectorEntry variable=\"ShaftResolution\" type=\"int\" help=\"Set the number of faces on shaft\"/>\n"
"  <VectorEntry variable=\"ShaftRadius\" type=\"float\" help=\"Set the radius of the shaft\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"Axes\" root_name=\"Axes\" output=\"vtkPolyData\" module_type=\"Source\">\n"
"  <Source type=\"vtkAxes\"/>\n"
"  <VectorEntry label=\"Scale\" variable=\"ScaleFactor\" type=\"float\" help=\"Set the size of the axes\"/>\n"
"  <VectorEntry variable=\"Origin\" type=\"float\" length=\"3\" help=\"Set the x, y, z coordinates of the origin of the axes\"/>\n"
"  <LabeledToggle variable=\"Symmetric\" help=\"Select whether to display the negative axes\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"ConeSource\" root_name=\"Cone\" output=\"vtkPolyData\" module_type=\"Source\">\n"
"  <Source type=\"vtkConeSource\"/>\n"
"  <VectorEntry variable=\"Resolution\" type=\"int\" help=\"Set the number of faces on this cone\"/>\n"
"  <VectorEntry variable=\"Radius\" type=\"float\" help=\"Set the radius of the widest part of the cone\"/>\n"
"  <VectorEntry variable=\"Height\" type=\"float\" help=\"Set the height of the cone\"/>\n"
"  <LabeledToggle variable=\"Capping\" help=\"Set whether to draw the base of the cone\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"CubeSource\" root_name=\"Cube\" output=\"vtkPolyData\" module_type=\"Source\">\n"
"  <Source type=\"vtkCubeSource\"/>\n"
"  <VectorEntry variable=\"XLength\" type=\"int\" help=\"The length of the cube in the x direction.\"/>\n"
"  <VectorEntry variable=\"YLength\" type=\"int\" help=\"The length of the cube in the y direction.\"/>\n"
"  <VectorEntry variable=\"ZLength\" type=\"int\" help=\"The length of the cube in the z direction.\"/>\n"
"  <VectorEntry variable=\"Center\" type=\"float\" length=\"3\" help=\"Set the center of the cube.\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"CylinderSource\" root_name=\"Cyl\" output=\"vtkPolyData\" module_type=\"Source\">\n"
"  <Source type=\"vtkCylinderSource\"/>\n"
"  <VectorEntry variable=\"Resolution\" type=\"int\" help=\"The number of facets used to define the cylinder.\"/>\n"
"  <VectorEntry variable=\"Height\" type=\"float\" help=\"The height of the cylinder (along the y axis).\"/>\n"
"  <VectorEntry variable=\"Radius\" type=\"float\" help=\"The radius of the cylinder.\"/>\n"
"  <VectorEntry variable=\"Center\" type=\"float\" length=\"3\" help=\"Set the center of the cylinder.\"/>\n"
"  <LabeledToggle variable=\"Capping\" help=\"Set whether to draw the ends of the cylinder\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"ImageMandelbrotSource\" root_name=\"Fractal\" output=\"vtkImageData\" module_type=\"Source\">\n"
"  <Source type=\"vtkImageMandelbrotSource\"/>\n"
"  <VectorEntry label=\"Extent\" variable=\"WholeExtent\" type=\"int\" length=\"6\" help=\"Set the min and max values of the data in each dimension\"/>\n"
"  <VectorEntry label=\"SubSpace\" variable=\"ProjectionAxes\" type=\"int\" length=\"3\" help=\"Choose which axes of the data set to display\"/>\n"
"  <VectorEntry label=\"Origin\" variable=\"OriginCX\" type=\"float\" length=\"4\" help=\"Set the imaginary and real values for C (constant) and X (initial value)\"/>\n"
"  <VectorEntry label=\"Size\" variable=\"SizeCX\" type=\"float\" length=\"4\" help=\"Set the inaginary and real values for the world size of the volume for C (constant) and X (initial value)\"/>\n"
"  <VectorEntry label=\"MaxIterations\" variable=\"MaximumNumberOfIterations\" type=\"int\" help=\"The limit on computational iterations. Values less than 2.0 after this many iterations are considered in the set.\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"ImageReader\" root_name=\"ImageRead\" output=\"vtkImageData\" module_type=\"Source\">\n"
"  <Source type=\"vtkImageReader\"/>\n"
"  <FileEntry variable=\"FilePrefix\" extension=\"\" help=\"Set the file root. Used with file pattern to format a file name.\"/>  \n"
"  <StringEntry variable=\"FilePattern\" help=\"Set the format string.\"/>\n"
"  <SelectionList variable=\"DataScalarType\" help=\"Select the pixel type in the file: short, int, float ...\">\n"
"    <Item name=\"char\" value=\"1\"/>\n"
"    <Item name=\"unsigned char\" value=\"2\"/>\n"
"    <Item name=\"short\" value=\"3\"/>\n"
"    <Item name=\"unsigned short\" value=\"4\"/>\n"
"    <Item name=\"int\" value=\"5\"/>\n"
"    <Item name=\"unsigned int\" value=\"6\"/>\n"
"    <Item name=\"long\" value=\"7\"/>\n"
"    <Item name=\"unsigned short\" value=\"8\"/>\n"
"    <Item name=\"unsigned long\" value=\"9\"/>\n"
"    <Item name=\"float\" value=\"10\"/>\n"
"    <Item name=\"double\" value=\"11\"/>\n"
"  </SelectionList>\n"
"  <SelectionList variable=\"DataByteOrder\" help=\"Select the pixel type in the file: short, int, float ...\">\n"
"    <Item name=\"big endian\" value=\"0\"/>\n"
"    <Item name=\"little endian\" value=\"1\"/>\n"
"  </SelectionList>\n"
"  <VectorEntry label=\"Extent\" variable=\"DataExtent\" type=\"int\" length=\"6\" help=\"Set the min and max values of the data in each dimension\"/>\n"
"  <VectorEntry variable=\"NumberOfScalarComponents\" type=\"int\" help=\"How many componenets does each pixel have. (i.e. RGB would be 3.)\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"OutlineCornerSource\" root_name=\"Corners\" output=\"vtkPolyData\" module_type=\"Source\">\n"
"  <Source type=\"vtkOutlineCornerSource\"/>\n"
"  <VectorEntry variable=\"Bounds\" type=\"float\" length=\"6\" help=\"Bounds of the outline.\"/>\n"
"  <VectorEntry variable=\"CornerFactor\" type=\"float\" help=\"The relative size of the corners to the length of the corresponding bounds. (0.001 -> 0.5)\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"ParticleReader\" root_name=\"Particle\" output=\"vtkPolyData\" module_type=\"Source\">\n"
"  <Source type=\"vtkParticleReader\"/>\n"
"  <FileEntry variable=\"FileName\" extension=\"*\" help=\"Set the file to read.\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"PLOT3DReader\" root_name=\"Plot3D\" output=\"vtkStructuredGrid\" module_type=\"Source\">\n"
"  <Source type=\"vtkPLOT3DReader\"/>\n"
"  <FileEntry variable=\"XYZFileName\" extension=\"bin\" help=\"Set the geometry file to read.\"/>  \n"
"  <FileEntry variable=\"QFileName\" extension=\"bin\" help=\"Set the data file to read.\"/>\n"
"  <VectorEntry variable=\"ScalarFunctionNumber\" type=\"int\" help=\"PLOT3D number for scalars\"/>\n"
"  <VectorEntry variable=\"VectorFunctionNumber\" type=\"int\" help=\"PLOT3D number for vectors\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"POPReader\" root_name=\"POPReader\" output=\"vtkStructuredGrid\" module_type=\"Source\">\n"
"  <Source type=\"vtkPOPReader\"/>\n"
"  <FileEntry variable=\"FileName\" extension=\"pop\" help=\"Select the file for the data set\"/>\n"
"  <VectorEntry variable=\"Radius\" type=\"float\" help=\"Set the radius of the data set\"/>\n"
"  <VectorEntry variable=\"ClipExtent\" type=\"int\" length=\"6\" help=\"For reading a smaller extent.\"/>\n"
"  <VectorEntry variable=\"NumberOfGhostLevels\" type=\"int\" help=\"Set the number of ghost levels to read.\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"RTAnalyticSource\" root_name=\"RTSource\" output=\"vtkStructuredPoints\" module_type=\"Source\">\n"
"  <Source type=\"vtkRTAnalyticSource\"/>\n"
"  <VectorEntry variable=\"WholeExtent\" type=\"int\" length=\"6\" help=\"Extent (dimensions) of the function.\"/>\n"
"  <VectorEntry variable=\"Center\" type=\"int\" length=\"3\" help=\"Center of the function.\"/>\n"
"  <VectorEntry variable=\"Maximum\" type=\"float\" help=\"Maximum value of the function\"/>\n"
"  <VectorEntry variable=\"XFreq\" type=\"float\" help=\"Frequency in X\"/>\n"
"  <VectorEntry variable=\"YFreq\" type=\"float\" help=\"Frequency in Y\"/>\n"
"  <VectorEntry variable=\"ZFreq\" type=\"float\" help=\"Frequency in Z\"/>\n"
"  <VectorEntry variable=\"XMag\" type=\"float\" help=\"Wave amplitude in X\"/>\n"
"  <VectorEntry variable=\"YMag\" type=\"float\" help=\"Wave amplitude in Y\"/>\n"
"  <VectorEntry variable=\"ZMag\" type=\"float\" help=\"Wave amplitude in Z\"/>\n"
"  <VectorEntry variable=\"StandardDeviation\" type=\"float\" help=\"Standard deviation of the gaussian\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"SphereSource\" root_name=\"Sphere\" output=\"vtkPolyData\" module_type=\"Source\">\n"
"  <Source type=\"vtkSphereSource\"/>\n"
"  <VectorEntry variable=\"Center\" type=\"float\" length=\"3\" help=\"Set the coordinates for the center of the sphere.\"/>\n"
"  <VectorEntry variable=\"Radius\" type=\"float\" help=\"Set the radius of the sphere\"/>\n"
"  <VectorEntry label=\"Theta Resolution\" variable=\"ThetaResolution\" type=\"int\" help=\"Set the number of points in the longitude direction (ranging from Start Theta to End Theta)\"/>\n"
"  <VectorEntry label=\"Start Theta\" variable=\"StartTheta\" type=\"float\" help=\"Set the starting angle in the longitude direction\"/>\n"
"  <VectorEntry label=\"End Theta\" variable=\"EndTheta\" type=\"float\" help=\"Set the ending angle in the longitude direction\"/>\n"
"  <VectorEntry label=\"Phi Resolution\" variable=\"PhiResolution\" type=\"int\" help=\"Set the number of points in the latitude direction (ranging from Start Phi to End Phi)\"/>\n"
"  <VectorEntry label=\"Start Phi\" variable=\"StartPhi\" type=\"float\" help=\"Set the starting angle in the latitude direction\"/>\n"
"  <VectorEntry label=\"End Phi\" variable=\"EndPhi\" type=\"float\" help=\"Set the ending angle in the latitude direction\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"STLReader\" root_name=\"STLReader\" output=\"vtkPolyData\" module_type=\"Source\">\n"
"  <Source type=\"vtkSTLReader\"/>\n"
"  <FileEntry variable=\"FileName\" extension=\"stl\" help=\"Select the data file for the STL data set\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"SuperquadricSource\" root_name=\"SQuad\" output=\"vtkPolyData\" module_type=\"Source\">\n"
"  <Source type=\"vtkSuperquadricSource\"/>\n"
"  <VectorEntry variable=\"Center\" type=\"float\" length=\"3\" help=\"Set the center of the superquadric\"/>\n"
"  <VectorEntry variable=\"Scale\" type=\"float\" length=\"3\" help=\"Set the scale of the superquadric\"/>\n"
"  <VectorEntry variable=\"ThetaResolution\" type=\"int\" help=\"The number of points in the longitude direction.\"/>\n"
"  <VectorEntry variable=\"PhiResolution\" type=\"int\" help=\"The number of points in the latitude direction.\"/>\n"
"  <VectorEntry variable=\"Thickness\" type=\"float\" help=\"Changing thickness maintains the outside diameter of the toroid.\"/>\n"
"  <VectorEntry variable=\"ThetaRoundness\" type=\"float\" help=\"Values range from 0 (rectangular) to 1 (circular) to higher order.\"/>\n"
"  <VectorEntry variable=\"PhiRoundness\" type=\"float\" help=\"Values range from 0 (rectangular) to 1 (circular) to higher order.\"/>\n"
"  <VectorEntry variable=\"Size\" type=\"float\" help=\"Isotropic size\"/>\n"
"  <LabeledToggle variable=\"Toroidal\" help=\"Whether or not the superquadric is toroidal or ellipsoidal\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"VectorText\" root_name=\"VectorText\" output=\"vtkPolyData\" module_type=\"Source\">\n"
"  <Source type=\"vtkVectorText\"/>\n"
"  <StringEntry variable=\"Text\" help=\"Enter the text to display\"/>\n"
"</Module>\n"
"\n"
"</ModuleInterfaces>\n";

// Define the standard filter interfaces.
const char* vtkPVWindow::StandardFilterInterfaces=
"<ModuleInterfaces>\n"




"<Module name=\"Balance\" root_name=\"Balance\" input=\"vtkPolyData\" output=\"vtkPolyData\" module_type=\"Filter\">\n"
"  <Filter type=\"vtkBalanceRedistributePolyData\"/>\n"
"  <InputMenu label=\"Input\" help=\"Balance the number of cells on all processes.\"\n"
"             input_name=\"PVInput\" input_type=\"vtkPolyData\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"AllToN\" root_name=\"AllToN\" input=\"vtkPolyData\" output=\"vtkPolyData\" module_type=\"Filter\">\n"
"  <Filter type=\"vtkBalanceRedistributePolyData\"/>\n"
"  <InputMenu label=\"Input\" \n"
"             help=\"Redistribute polydata to a subset of processes.\"\n"
"             input_name=\"PVInput\" input_type=\"vtkPolyData\"/>\n"
"  <VectorEntry variable=\"NumberOfProcesses\" type=\"int\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"AllToN\" root_name=\"AllToN\" input=\"vtkPolyData\" output=\"vtkPolyData\" module_type=\"Filter\">\n"
"  <Filter type=\"vtkBalanceRedistributePolyData\"/>\n"
"  <InputMenu label=\"Input\" \n"
"             help=\"Redistribute polydata to a subset of processes.\"\n"
"             input_name=\"PVInput\" input_type=\"vtkPolyData\"/>\n"
"  <VectorEntry variable=\"NumberOfProcesses\" type=\"int\"/>\n"
"</Module>\n"
"\n"




"<Module name=\"BrownianPoints\" root_name=\"BPts\" input=\"vtkDataSet\" output=\"vtkDataSet\" module_type=\"Filter\">\n"
"  <Filter type=\"vtkBrownianPoints\"/>\n"
"  <InputMenu label=\"Input\" help=\"Set the input to this filter.\"\n"
"             input_name=\"PVInput\" input_type=\"vtkDataSet\"/>\n"
"  <VectorEntry variable=\"MinimumSpeed\" type=\"float\" help=\"The minimum size of the random point vectors generated.\"/>\n"
"  <VectorEntry variable=\"MaximumSpeed\" type=\"float\" help=\"The maximum size of the random point vectors generated.\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"CellCenters\" root_name=\"Centers\" input=\"vtkDataSet\" output=\"vtkPolyData\" module_type=\"Filter\">\n"
"  <Filter type=\"vtkCellCenters\"/>\n"
"  <InputMenu label=\"Input\" help=\"Set the input to this filter.\"\n"
"             input_name=\"PVInput\" input_type=\"vtkDataSet\"/>\n"
"  <LabeledToggle variable=\"VertexCells\" help=\"Generate vertex as geometry of just points.\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"PCellDataToPointData\" root_name=\"CellToPoint\" input=\"vtkDataSet\" output=\"vtkDataSet\" module_type=\"Filter\">\n"
"  <Filter type=\"vtkPCellDataToPointData\"/>\n"
"  <InputMenu label=\"Input\" help=\"Set the input to this filter.\"\n"
"             input_name=\"PVInput\" input_type=\"vtkDataSet\"/>\n"
"  <LabeledToggle variable=\"PassCellData\" help=\" Control whether the input cell data is to be passed to the output. If on, then the input cell data is passed through to the output; otherwise, only generated point data is placed into the output.\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"CleanPolyData\" root_name=\"CleanPD\" input=\"vtkPolyData\" output=\"vtkPolyData\" module_type=\"Filter\">\n"
"  <Filter type=\"vtkCleanPolyData\"/>\n"
"  <InputMenu label=\"Input\" help=\"Set the input to this filter.\"\n"
"             input_name=\"PVInput\" input_type=\"vtkPolyData\"/>\n"
"  <LabeledToggle variable=\"PieceInvariant\" help=\"Turn this off if you do not want pieces or do not mind seams.\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"DataSetSurfaceFilter\" root_name=\"Surface\" input=\"vtkDataSet\" output=\"vtkPolyData\" module_type=\"Filter\">\n"
"  <Filter type=\"vtkDataSetSurfaceFilter\"/>\n"
"  <InputMenu label=\"Input\" help=\"Set the input to this filter.\"\n"
"             input_name=\"PVInput\" input_type=\"vtkDataSet\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"DataSetTriangleFilter\" root_name=\"Tetra\" input=\"vtkDataSet\" output=\"vtkUnstructuredGrid\" module_type=\"Filter\">\n"
"  <Filter type=\"vtkDataSetTriangleFilter\"/>\n"
"  <InputMenu label=\"Input\" help=\"Set the input to this filter.\"\n"
"             input_name=\"PVInput\" input_type=\"vtkDataSet\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"DecimatePro\" root_name=\"Deci\" input=\"vtkPolyData\" output=\"vtkPolyData\" module_type=\"Filter\">\n"
"  <Filter type=\"vtkDecimatePro\"/>\n"
"  <InputMenu label=\"Input\" help=\"Set the input to this filter.\"\n"
"             input_name=\"PVInput\" input_type=\"vtkPolyData\"/>\n"
"  <VectorEntry variable=\"TargetReduction\" type=\"float\" help=\"Value between 0 and 1. Desired reduction of the total number of triangles.\"/>\n"
"  <LabeledToggle variable=\"PreserveTopology\" help=\"If off, better reduction can occur, but model may break up.\"/>\n"
"  <VectorEntry variable=\"FeatureAngle\" type=\"float\" help=\"Topology can be split along features.\"/>\n"
"  <LabeledToggle variable=\"BoundaryVertexDeletion\" help=\"If off, decimate will not remove points on the boundary.\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"ElevationFilter\" root_name=\"Elevation\" input=\"vtkDataSet\" output=\"vtkDataSet\" module_type=\"Filter\">\n"
"  <Filter type=\"vtkElevationFilter\"/>\n"
"  <InputMenu label=\"Input\" help=\"Set the input to this filter.\"\n"
"             input_name=\"PVInput\" input_type=\"vtkDataSet\"/>\n"
"  <VectorEntry variable=\"LowPoint\" type=\"float\" length=\"3\" help=\"Set the minimum point for the elevation\"/>\n"
"  <VectorEntry variable=\"HighPoint\" type=\"float\" length=\"3\" help=\"Set the maximum point for the elevation\"/>\n"
"  <VectorEntry variable=\"ScalarRange\" type=\"float\" length=\"2\" help=\"Set the range of scalar values to generate\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"ExtractEdges\" root_name=\"ExtractEdges\" input=\"vtkDataSet\" output=\"vtkPolyData\" module_type=\"Filter\">\n"
"  <Filter type=\"vtkExtractEdges\"/>\n"
"  <InputMenu label=\"Input\" help=\"Set the input to this filter.\"\n"
"             input_name=\"PVInput\" input_type=\"vtkDataSet\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"ExtractGrid\" root_name=\"ExtractGrid\" input=\"vtkStructuredGrid\" output=\"vtkStructuredGrid\" module_type=\"Filter\">\n"
"  <Filter type=\"vtkExtractGrid\"/>\n"
"  <InputMenu label=\"Input\" help=\"Set the input to this filter.\"\n"
"             input_name=\"PVInput\" input_type=\"vtkStructuredGrid\"/>\n"
"  <ExtentEntry variable=\"VOI\" help=\"Set the min/max values of the volume of interest (VOI)\"/>\n"
"  <VectorEntry variable=\"SampleRate\" type=\"int\" length=\"3\" help=\"Set the sampling rate for each dimension\"/>\n"
"  <LabeledToggle variable=\"IncludeBoundary\" help=\"Select whether to always include the boundary of the grid in the output\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"ExtractRectilinearGrid\" root_name=\"ExtractRGrid\" input=\"vtkRectilinearGrid\" output=\"vtkRectilinearGrid\" module_type=\"Filter\">\n"
"  <Filter type=\"vtkExtractRectilinearGrid\"/>\n"
"  <InputMenu label=\"Input\" help=\"Set the input to this filter.\"\n"
"             input_name=\"PVInput\" input_type=\"vtkRectilinearGrid\"/>\n"
"  <ExtentEntry variable=\"VOI\" help=\"Set the min/max values of the volume of interest (VOI)\"/>\n"
"  <VectorEntry variable=\"SampleRate\" type=\"int\" length=\"3\" help=\"Set the sampling rate for each dimension\"/>\n"
"  <LabeledToggle variable=\"IncludeBoundary\" help=\"Select whether to always include the boundary of the grid in the output\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"ImageGaussianSmooth\" root_name=\"GaussSmooth\" input=\"vtkImageData\" output=\"vtkImageData\" module_type=\"Filter\">\n"
"  <Filter type=\"vtkImageGaussianSmooth\"/>\n"
"  <InputMenu label=\"Input\" help=\"Set the input to this filter.\"\n"
"             input_name=\"PVInput\" input_type=\"vtkImageData\"/>\n"
"  <VectorEntry variable=\"StandardDeviations\" type=\"float\" length=\"3\" help=\"STD for x, y and z axes.\"/>\n"
"  <VectorEntry variable=\"RadiusFactors\" type=\"float\" length=\"3\" help=\"Kernel size is this factor times STD.\"/>\n"
"  <SelectionList variable=\"Dimensionality\" help=\"Select whether to perform a 2d or 3d gradient\">\n"
"    <Item name=\"2\" value=\"0\"/>\n"
"    <Item name=\"3\" value=\"1\"/>\n"
"  </SelectionList>\n"
"</Module>\n"
"\n"
"<Module name=\"ImageClip\" root_name=\"ImageClip\" input=\"vtkImageData\" output=\"vtkImageData\" module_type=\"Filter\">\n"
"  <Filter type=\"vtkImageClip\"/>\n"
"  <InputMenu label=\"Input\" help=\"Set the input to this filter.\"\n"
"             input_name=\"PVInput\" input_type=\"vtkImageData\"/>\n"
"  <ExtentEntry variable=\"OutputWholeExtent\" help=\"Set the min/max extents in each dimension of the output\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"PLinearExtrusionFilter\" root_name=\"LinExtrude\" input=\"vtkPolyData\" output=\"vtkPolyData\" module_type=\"Filter\">\n"
"  <Filter type=\"vtkPLinearExtrusionFilter\"/>\n"
"  <InputMenu label=\"Input\" help=\"Set the input to this filter.\"\n"
"             input_name=\"PVInput\" input_type=\"vtkPolyData\"/>\n"
"  <VectorEntry variable=\"ScaleFactor\" type=\"float\" help=\"Set the extrusion scale factor\"/>\n"
"  <VectorEntry variable=\"Vector\" type=\"float\" length=\"3\" help=\"Set the direction for the extrusion\"/>\n"
"  <LabeledToggle variable=\"Capping\" help=\"Select whether to draw endcaps\"/>\n"
"  <LabeledToggle variable=\"PieceInvariant\" help=\"Turn this off if you do want to process ghost levels and do not mind seams.\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"LoopSubdivisionFilter\" root_name=\"LoopSubDiv\" input=\"vtkPolyData\" output=\"vtkPolyData\" module_type=\"Filter\">\n"
"  <Filter type=\"vtkLoopSubdivisionFilter\"/>\n"
"  <InputMenu label=\"Input\" help=\"Set the input to this filter.\"\n"
"             input_name=\"PVInput\" input_type=\"vtkPolyData\"/>\n"
"  <VectorEntry variable=\"NumberOfSubdivisions\" type=\"int\" help=\"Each subdivision changes single triangles into four triangles.\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"MaskPoints\" root_name=\"MaskPts\" input=\"vtkDataSet\" output=\"vtkPolyData\" module_type=\"Filter\">\n"
"  <Filter type=\"vtkMaskPoints\"/>\n"
"  <InputMenu label=\"Input\" help=\"Set the input to this filter.\"\n"
"             input_name=\"PVInput\" input_type=\"vtkDataSet\"/>\n"
"  <VectorEntry variable=\"OnRatio\" type=\"int\" help=\"The ratio of points retained.\"/>\n"
"  <VectorEntry label=\"MaxPoints\" variable=\"MaximumNumberOfPoints\" type=\"int\" help=\"Limit the number of points.\"/>\n"
"  <VectorEntry variable=\"Offset\" type=\"int\" help=\"Start with this point.\"/>\n"
"  <LabeledToggle label=\"Random\" variable=\"RandomMode\" help=\"Select whether to randomly select points, or subsample regularly.\"/>\n"
"  <LabeledToggle variable=\"GenerateVertices\" help=\"Convienience feature to display points.\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"OutlineCornerFilter\" root_name=\"COutline\" input=\"vtkDataSet\" output=\"vtkPolyData\" module_type=\"Filter\">\n"
"  <Filter type=\"vtkOutlineCornerFilter\"/>\n"
"  <InputMenu label=\"Input\" help=\"Set the input to this filter.\"\n"
"             input_name=\"PVInput\" input_type=\"vtkDataSet\"/>\n"
"  <VectorEntry variable=\"CornerFactor\" type=\"float\" help=\"The relative size of the corners to the length of the corresponding bounds. (0.001 -> 0.5)\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"PieceScalars\" root_name=\"ColorPieces\" input=\"vtkDataSet\" output=\"vtkDataSet\" module_type=\"Filter\">\n"
"  <Filter type=\"vtkPieceScalars\"/>\n"
"  <InputMenu label=\"Input\" help=\"Set the input to this filter.\"\n"
"             input_name=\"PVInput\" input_type=\"vtkDataSet\"/>\n"
"  <LabeledToggle label=\"Random\" variable=\"RandomMode\" help=\"Select whether to use random colors for the various pieces\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"PPolyDataNormals\" root_name=\"PDNormals\" input=\"vtkPolyData\" output=\"vtkPolyData\" module_type=\"Filter\">\n"
"  <Filter type=\"vtkPPolyDataNormals\"/>\n"
"  <InputMenu label=\"Input\" help=\"Set the input to this filter.\"\n"
"             input_name=\"PVInput\" input_type=\"vtkPolyData\"/>\n"
"  <VectorEntry variable=\"FeatureAngle\" type=\"float\" help=\"Points are duplicated along features over this angle (0->180)\"/>\n"
"  <LabeledToggle variable=\"Splitting\" help=\"Turn on/off the splitting of sharp edges.\"/>\n"
"  <LabeledToggle variable=\"Consistency\" help=\"Turn on/off the enforcement of consistent polygon ordering.\"/>\n"
"  <LabeledToggle label=\"CellNormals\" variable=\"ComputeCellNormals\" help=\"Turn on/off the computation of cell normals.\"/>\n"
"  <LabeledToggle variable=\"FlipNormals\" help=\"Flipping reverves the meaning of front and back.\"/>\n"
"  <LabeledToggle label=\"NonManifold\" variable=\"NonManifoldTraversal\" help=\"Turn on/off traversal across non-manifold edges. This will prevent problems where the consistency of polygonal ordering is corrupted due to topological loops.\"/>\n"
"  <LabeledToggle variable=\"PieceInvariant\" help=\"Turn this off if you do not want to process ghost levels and do not mind seams.\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"PVConnectivityFilter\" root_name=\"Connect\" input=\"vtkDataSet\" output=\"vtkUnstructuredGrid\" module_type=\"Filter\">\n"
"  <Filter type=\"vtkPVConnectivityFilter\"/>\n"
"  <InputMenu label=\"Input\" help=\"Set the input to this filter.\"\n"
"             input_name=\"PVInput\" input_type=\"vtkDataSet\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"QuadricClustering\" root_name=\"QC\" input=\"vtkPolyData\" output=\"vtkPolyData\" module_type=\"Filter\">\n"
"  <Filter type=\"vtkQuadricClustering\"/>\n"
"  <InputMenu label=\"Input\" help=\"Set the input to this filter.\"\n"
"             input_name=\"PVInput\" input_type=\"vtkPolyData\"/>\n"
"  <VectorEntry label=\"Spacing\" variable=\"DivisionSpacing\" type=\"float\" length=\"3\" help=\"Set the spacing of the bins in each dimension\"/>\n"
"  <LabeledToggle variable=\"UseInputPoints\" help=\"Select whether to use points from the input in the output or to calculate optimum representative points for each bin\"/>\n"
"  <LabeledToggle variable=\"UseFeatureEdges\" help=\"Select whether to use feature edge quadrics to match up the boundaries between pieces\"/>\n"
"  <LabeledToggle variable=\"UseFeaturePoints\" help=\"Select whether to use feature point quadrics to align piece boundaries\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"RectilinearGridGeometryFilter\" root_name=\"RectGridGeom\" input=\"vtkRectilinearGrid\" output=\"vtkPolyData\" module_type=\"Filter\">\n"
"  <Filter type=\"vtkRectilinearGridGeometryFilter\"/>\n"
"  <InputMenu label=\"Input\" help=\"Set the input to this filter.\"\n"
"             input_name=\"PVInput\" input_type=\"vtkRectilinearGrid\"/>\n"
"  <ExtentEntry variable=\"Extent\" help=\"Set the min/max extents of the grid\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"ReflectionFilter\" root_name=\"Reflect\" input=\"vtkDataSet\" output=\"vtkUnstructuredGrid\" module_type=\"Filter\">\n"
"  <Filter type=\"vtkReflectionFilter\"/>\n"
"  <InputMenu label=\"Input\" help=\"Set the input to this filter.\"\n"
"             input_name=\"PVInput\" input_type=\"vtkPolyData\"/>\n"
"  <SelectionList variable=\"Plane\" help=\"Select which plane of the bounding box to reflect across\">\n"
"    <Item name=\"X Min\" value=\"0\"/>\n"
"    <Item name=\"Y Min\" value=\"1\"/>\n"
"    <Item name=\"Z Min\" value=\"2\"/>\n"
"    <Item name=\"X Max\" value=\"3\"/>\n"
"    <Item name=\"Y Max\" value=\"4\"/>\n"
"    <Item name=\"Z Max\" value=\"5\"/>\n"
"  </SelectionList>\n"
"</Module>\n"
"\n"
"<Module name=\"RibbonFilter\" root_name=\"Ribbon\" input=\"vtkPolyData\" output=\"vtkPolyData\" module_type=\"Filter\">\n"
"  <Filter type=\"vtkRibbonFilter\"/>\n"
"  <InputMenu label=\"Input\" help=\"Set the input to this filter.\"\n"
"             input_name=\"PVInput\" input_type=\"vtkPolyData\"/>\n"
"  <VectorEntry variable=\"Width\" type=\"float\" help=\"The half width of the ribbon (or minimum).\"/>\n"
"  <VectorEntry variable=\"Angle\" type=\"float\" help=\"The offset angle of the ribbon from the line normal (0->360).\"/>\n"
"  <VectorEntry variable=\"DefaultNormal\" type=\"float\" length=\"3\" help=\"If no normals are supplied\"/>\n"
"  <LabeledToggle variable=\"VaryWidth\" help=\"Turn on/off the variation of ribbon width with scalar value.\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"RotationalExtrusionFilter\" root_name=\"RotExtrude\" input=\"vtkPolyData\" output=\"vtkPolyData\" module_type=\"Filter\">\n"
"  <Filter type=\"vtkRotationalExtrusionFilter\"/>\n"
"  <InputMenu label=\"Input\" help=\"Set the input to this filter.\"\n"
"             input_name=\"PVInput\" input_type=\"vtkPolyData\"/>\n"
"  <VectorEntry variable=\"Resolution\" type=\"int\"/>\n"
"  <LabeledToggle variable=\"Capping\"/>\n"
"  <VectorEntry variable=\"Angle\" type=\"float\" help=\"Set the angle of rotation.\"/>\n"
"  <VectorEntry variable=\"Translation\" type=\"float\" help=\"The total amount of translation along the z-axis.\"/>\n"
"  <VectorEntry variable=\"DeltaRadius\" type=\"float\" help=\"The change in radius during sweep process.\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"ShrinkFilter\" root_name=\"Shrink\" input=\"vtkDataSet\" output=\"vtkUnstructuredGrid\" module_type=\"Filter\">\n"
"  <Filter type=\"vtkShrinkFilter\"/>\n"
"  <InputMenu label=\"Input\" help=\"Set the input to this filter.\"\n"
"             input_name=\"PVInput\" input_type=\"vtkDataSet\"/>\n"
"  <VectorEntry variable=\"ShrinkFactor\" type=\"float\" help=\"Set the amount to shrink by\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"ShrinkPolyData\" root_name=\"ShrinkPD\" input=\"vtkPolyData\" output=\"vtkPolyData\" module_type=\"Filter\">\n"
"  <Filter type=\"vtkShrinkPolyData\"/>\n"
"  <InputMenu label=\"Input\" help=\"Set the input to this filter.\"\n"
"             input_name=\"PVInput\" input_type=\"vtkPolyData\"/>\n"
"  <VectorEntry variable=\"ShrinkFactor\" type=\"float\" help=\"Set the amount to shrink by\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"SmoothPolyDataFilter\" root_name=\"Smooth\" input=\"vtkPolyData\" output=\"vtkPolyData\" module_type=\"Filter\">\n"
"  <Filter type=\"vtkSmoothPolyDataFilter\"/>\n"
"  <InputMenu label=\"Input\" help=\"Set the input to this filter.\"\n"
"             input_name=\"PVInput\" input_type=\"vtkPolyData\"/>\n"
"  <VectorEntry variable=\"NumberOfIterations\" type=\"int\" help=\"More iterations produces better smoothing.\"/>\n"
"  <VectorEntry variable=\"Convergence\" type=\"float\" help=\"Smooting factor (0->1).\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"Stripper\" root_name=\"Strip\" input=\"vtkPolyData\" output=\"vtkPolyData\" module_type=\"Filter\">\n"
"  <Filter type=\"vtkStripper\"/>\n"
"  <InputMenu label=\"Input\" help=\"Set the input to this filter.\"\n"
"             input_name=\"PVInput\" input_type=\"vtkPolyData\"/>\n"
"  <VectorEntry variable=\"MaximumLength\" type=\"int\" help=\"Stop stripping after this many triangles.\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"StructuredGridGeometryFilter\" root_name=\"StruGridGeom\" input=\"vtkStructuredGrid\" output=\"vtkPolyData\" module_type=\"Filter\">\n"
"  <Filter type=\"vtkStructuredGridGeometryFilter\"/>\n"
"  <InputMenu label=\"Input\" help=\"Set the input to this filter.\"\n"
"             input_name=\"PVInput\" input_type=\"vtkStructuredGrid\"/>\n"
"  <VectorEntry variable=\"Extent\" type=\"int\" length=\"6\" help=\"Set the min/max extents of the grid\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"StructuredGridOutlineFilter\" root_name=\"GOutline\" input=\"vtkStructuredGrid\" output=\"vtkPolyData\" module_type=\"Filter\">\n"
"  <Filter type=\"vtkStructuredGridOutlineFilter\"/>\n"
"  <InputMenu label=\"Input\" help=\"Set the input to this filter.\"\n"
"             input_name=\"PVInput\" input_type=\"vtkStructuredGrid\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"TriangleFilter\" root_name=\"Tri\" input=\"vtkPolyData\" output=\"vtkPolyData\" module_type=\"Filter\">\n"
"  <Filter type=\"vtkTriangleFilter\"/>\n"
"  <InputMenu label=\"Input\" help=\"Set the input to this filter.\"\n"
"             input_name=\"PVInput\" input_type=\"vtkPolyData\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"TubeFilter\" root_name=\"Tuber\" input=\"vtkPolyData\" output=\"vtkPolyData\" module_type=\"Filter\">\n"
"  <Filter type=\"vtkTubeFilter\"/>\n"
"  <InputMenu label=\"Input\" help=\"Set the input to this filter.\"\n"
"             input_name=\"PVInput\" input_type=\"vtkPolyData\"/>\n"
"  <VectorEntry variable=\"NumberOfSides\" type=\"int\" help=\"Set the number of sides for the tube\"/>\n"
"  <LabeledToggle variable=\"Capping\" help=\"Select whether to draw endcaps on the tube\"/>\n"
"  <VectorEntry variable=\"Radius\" type=\"float\" help=\"Set the radius of the tube\"/>\n"
"  <SelectionList variable=\"VaryRadius\" help=\"Select whether/how to vary the radius of the tube\">\n"
"    <Item name=\"Off\" value=\"0\"/>\n"
"    <Item name=\"ByScalar\" value=\"1\"/>\n"
"    <Item name=\"ByVector\" value=\"2\"/>\n"
"  </SelectionList>\n"
"  <VectorEntry variable=\"RadiusFactor\" type=\"float\" help=\"Set the maximum tube radius in terms of a multiple of the minimum radius\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"WarpScalar\" root_name=\"WarpS\" input=\"vtkPointSet\" output=\"vtkPointSet\" default=\"scalars\" module_type=\"Filter\">\n"
"  <Filter type=\"vtkWarpScalar\"/>\n"
"  <InputMenu id=\"im\" label=\"Input\"\n"
"             help=\"Set the input to this filter.\"\n"
"             input_name=\"PVInput\" input_type=\"vtkPointSet\"/>\n"
"  <ArrayMenu input_name=\"Input\" attribute_type=\"Scalars\"\n"
"             label=\"Scalars\" input_menu=\"im\"\n"
"             help=\"Select the input scalars to process.\"/>\n"
"  <VectorEntry variable=\"ScaleFactor\" type=\"float\" help=\"Displacement is vector times scale.\"/>\n"
"  <VectorEntry variable=\"Normal\" type=\"float\" length=\"3\" help=\"Warp direction.\"/>\n"
"  <LabeledToggle variable=\"UseNormal\" help=\"Use instance model normals rather than instance normal.\"/>\n"
"  <LabeledToggle variable=\"XYPlane\" help=\"Z value is used to warp the surface, scalars to color surface.\"/>\n"
"</Module>\n"
"\n"
"<Module name=\"WarpVector\" root_name=\"WarpV\" input=\"vtkPointSet\" output=\"vtkPointSet\" default=\"vectors\" module_type=\"Filter\">\n"
"  <Filter type=\"vtkWarpVector\"/>\n"
"  <InputMenu id=\"im\" label=\"Input\"\n"
"             help=\"Set the input to this filter.\"\n"
"             input_name=\"PVInput\" input_type=\"vtkPointSet\"/>\n"
"  <ArrayMenu input_name=\"Input\" attribute_type=\"Vectors\"\n"
"             label=\"Vectors\" input_menu=\"im\" number_of_components=\"3\"\n"
"             help=\"Select the input vectors to process.\"/>\n"
"  <VectorEntry variable=\"ScaleFactor\" type=\"float\" help=\"Displacement is vector times scale.\"/>\n"
"</Module>\n"
"\n"
"  <Module name=\"ExtractVoids\" class=\"vtkPVExtractGeometryByScalar\" \n"
"          root_name=\"ExtractVoids\"\n"
"          output=\"vtkUnstructuredGrid\" input=\"vtkUnstructuredGrid\" module_type=\"Filter\">\n"
"    <Filter type=\"vtkKWExtractGeometryByScalar\"/>\n"
"  </Module>\n"
"  <Module name=\"Calculator\" class=\"vtkPVArrayCalculator\"\n"
"          root_name=\"Calc\" button_image=\"PVCalculatorButton\"\n"
"          button_help=\"Create new arrays using mathematical "
"operations and existing arrays.\"\n"
"          output=\"vtkDataSet\" input=\"vtkDataSet\"\n"
"           module_type=\"Filter\">\n"
"    <Filter type=\"vtkArrayCalculator\"/>\n"
"  </Module>\n"
"  <Module name=\"Cut\" root_name=\"Cut\" replace_input=\"0\"\n" 
"          output=\"vtkPolyData\" input=\"vtkDataSet\"\n"
"          module_type=\"Filter\" button_image=\"PVCutButton\"\n"
"          button_help=\"Cut with an implicit plane or sphere. "
"Cutting typically reduces the dimensionality of the data.\">\n"
"    <Filter type=\"vtkCutter\"/>\n"
"    <InputMenu id=\"im1\" label=\"Input\" help=\"Set the input to this "
"filter.\"\n"
"               input_name=\"PVInput\" input_type=\"vtkDataSet\"/>\n"
"    <BoundsDisplay show_hide_frame=\"1\" label=\"Input Bounds\"\n"
"                   input_menu=\"im1\"/>\n"
"    <SelectWidget use_widget_command=\"1\" label=\"Cut Function\"\n"
"                  variable=\"CutFunction\">\n"
"      <Item label=\"Plane\" value=\"GetPlaneTclName\">\n"
"        <PlaneWidget/>\n"
"      </Item>\n"
"      <Item label=\"Sphere\" value=\"GetSphereTclName\">\n"
"        <SphereWidget/>\n"
"      </Item>\n"
"    </SelectWidget>\n"
"    <ContourEntry label=\"Cut Values\"/>\n"
"  </Module>\n"
"  <Module name=\"Clip\" root_name=\"Clip\"\n"
"          output=\"vtkUnstructuredGrid\" input=\"vtkDataSet\"\n"
"           module_type=\"Filter\" button_image=\"PVClipButton\"\n"
"           button_help=\"Clip with an implicit plane, sphere or with scalars."
" Clipping does not reduce the dimensionality of the data set.\">\n"
"    <Filter type=\"vtkClipDataSet\"/>\n"
"    <InputMenu id=\"im1\" label=\"Input\" \n"
"               help=\"Set the input to this filter.\"\n"
"               input_name=\"PVInput\" input_type=\"vtkDataSet\"/>\n"
"    <BoundsDisplay show_hide_frame=\"1\" label=\"Input Bounds\"\n"
"                   input_menu=\"im1\"/>\n"
"    <SelectWidget use_widget_command=\"1\" label=\"Clip Function\"\n"
"                  variable=\"ClipFunction\">\n"
"      <Item label=\"Plane\" value=\"GetPlaneTclName\">\n"
"        <PlaneWidget/>\n"
"      </Item>\n"
"      <Item label=\"Sphere\" value=\"GetSphereTclName\">\n"
"        <SphereWidget/>\n"
"      </Item>\n"
"      <Item label=\"Scalars\">\n"
"        <ContainerWidget>\n"
"         <Item>\n"
"           <ScalarRangeLabel array_menu=\"it3.am1\"/>\n"
"         </Item>\n"
"         <Item id=\"it3\">\n"
"           <ArrayMenu id=\"am1\" input_name=\"Input\"\n"
"                      attribute_type=\"Scalars\"\n"
"                      label=\"Scalars\"\n"
"                      help=\"Choose the clipping scalar array.\"\n"
"                      input_menu=\"im1\"/>\n"
"         </Item>\n"
"        </ContainerWidget>\n"
"      </Item>\n"
"    </SelectWidget>\n"
"    <VectorEntry label=\"Offset\" type=\"float\" variable=\"Value\"/>\n"
"    <LabeledToggle label=\"Inside Out\" variable=\"InsideOut\"\n"
"                   help=\"Switches which part to keep.\"/>\n"
"  </Module>\n"
"  <Module name=\"Threshold\" class=\"vtkPVThreshold\" \n"
"          root_name=\"Threshold\" button_image=\"PVThresholdButton\"\n"
"          button_help=\"Extract cells that satisfy a threshold criterion.\"\n"
"          output=\"vtkUnstructuredGrid\" input=\"vtkDataSet\"\n"
"          module_type=\"Filter\">\n"
"    <Filter type=\"vtkThreshold\"/>\n"
"  </Module>\n"
"  <Module name=\"Contour\" class=\"vtkPVContour\" \n"
"          root_name=\"Contour\" button_image=\"PVContourButton\"\n"
"          button_help=\"Generate isolines or isosurfaces.\"\n"
"          output=\"vtkPolyData\" input=\"vtkDataSet\"\n"
"          module_type=\"Filter\">\n"
#ifdef VTK_USE_PATENTED
"    <Filter type=\"vtkKitwareContourFilter\"/>\n"
#else
"    <Filter type=\"vtkContourFilter\"/>\n"
#endif
"  </Module>\n"
"  <Module name=\"Glyph\" class=\"vtkPVGlyph3D\" root_name=\"Glyph\" \n"
"          input=\"vtkDataSet\" output=\"vtkPolyData\"\n"
"          module_type=\"Filter\" button_image=\"PVGlyphButton\"\n"
"          button_help=\"Generate a glyph (symbol) at each point of "
"the dataset. These can be colored, scaled and oriented\">\n"
"    <Filter type=\"vtkGlyph3D\"/>\n"
"  </Module>\n"
"  <Module name=\"Probe\" class=\"vtkPVProbe\" \n"
"          root_name=\"Probe\" button_image=\"PVProbeButton\"\n"
"          button_help=\"Sample data values at specified points or along a"
"line\"\n"
"          output=\"vtkPolyData\" input=\"vtkDataSet\"\n"
"          module_type=\"Filter\">\n"
"    <Filter type=\"vtkProbeFilter\"/>\n"
"  </Module>\n"
"  <Module name=\"Pick\" \n"
"          root_name=\"Pick\"\n"
"          button_help=\"Pick cell or point closest to the widget\"\n"
"          output=\"vtkUnstructuredGrid\" input=\"vtkDataSet\"\n"
"          module_type=\"Filter\">\n"
"    <Filter type=\"vtkPickDataSetFilter\"/>\n"
"  <LabeledToggle variable=\"SearchCells\" help=\"Set when cells are supposed to be searched. Otherwise points will be searched.\"/>\n"
"  <PointWidget variable=\"SamplePoint\" help=\"Sample point that we are picking.\"/>\n"
"  </Module>\n"
"</ModuleInterfaces>\n";

// Define the standard manipulators.
const char* vtkPVWindow::StandardManipulators=
"<ModuleInterfaces>\n"
"  <Manipulator name=\"FlyIn\" types=\"3D\" class=\"vtkPVJoystickFlyIn\">\n"
"    <Scale variable=\"FlySpeed\" resolution=\".1\" range=\"1 30\" help=\"Set the speed of fly-in camera manipulation.\"/>\n"
"  </Manipulator>\n"
"\n"
"  <Manipulator name=\"FlyOut\" types=\"3D\" class=\"vtkPVJoystickFlyOut\">\n"
"    <Scale variable=\"FlySpeed\" resolution=\".1\" range=\"1 30\" help=\"Set the speed of fly-out camera manipulation.\"/>\n"
"  </Manipulator>\n"
"\n"
"  <Manipulator name=\"Rotate\" types=\"3D\" class=\"vtkPVTrackballRotate\">\n"
"  </Manipulator>\n"
"\n"
"  <Manipulator name=\"Roll\" types=\"2D 3D\" class=\"vtkPVTrackballRoll\">\n"
"  </Manipulator>\n"
"\n"
"  <Manipulator name=\"Pan\" types=\"2D 3D\" class=\"vtkPVTrackballPan\">\n"
"  </Manipulator>\n"
"\n"
"  <Manipulator name=\"Move\" types=\"2D 3D\" class=\"vtkPVTrackballMoveActor\">\n"
"  </Manipulator>\n"
"\n"
"  <Manipulator name=\"Zoom\" types=\"2D 3D\" class=\"vtkPVTrackballZoom\">\n"
"  </Manipulator>\n"
"\n"
"  <Manipulator name=\"Center\" types=\"3D\" class=\"vtkPVPivotManipulator\">\n"
"    <VectorEntry variable=\"CenterOfRotation\" type=\"int\" length=\"3\" \n"
"                 help=\"Reset the center of rotation\"/>\n"
"    <PushButton variable=\"ResetCenterOfRotation\" label=\"Reset Center Of Rotation\"\n"
"                 help=\"Reset the center of rotation\"/>\n"
"  </Manipulator>\n"
"</ModuleInterfaces>\n";


// Define the standard writers.
const char* vtkPVWindow::StandardWriters=
"<ModuleInterfaces>\n"
"  <Writer input=\"vtkDataSet\"\n"
"          class=\"vtkPVWriter\"\n"
"          writer=\"vtkDataSetWriter\"\n"
"          data_mode_method=\"SetFileTypeToBinary\"\n"
"          extension=\".vtk\"\n"
"          file_description=\"VTK Files\"/>\n"
"  <Writer input=\"vtkDataSet\"\n"
"          class=\"vtkPVWriter\"\n"
"          writer=\"vtkPDataSetWriter\"\n"
"          data_mode_method=\"SetFileTypeToBinary\"\n"
"          parallel=\"1\"\n"
"          extension=\".pvtk\"\n"
"          file_description=\"PVTK Files\"/>\n"
"</ModuleInterfaces>\n";

#endif
