NAME
  ParaView::VTKExtensionsExtractionPython
LIBRARY_NAME
  vtkPVVTKExtensionsExtractionPython
SPDX_LICENSE_IDENTIFIER
  BSD-3-Clause
SPDX_COPYRIGHT_TEXT
  Copyright (c) Kitware Inc.
DESCRIPTION
  Extraction filters that require Python
CONDITION
  PARAVIEW_USE_PYTHON
GROUPS
  PARAVIEW_CORE
KIT
  ParaView::CoreKit
DEPENDS
  VTK::FiltersExtraction
PRIVATE_DEPENDS
  VTK::WrappingPythonCore
  VTK::PythonInterpreter
  VTK::vtksys
TEST_LABELS
  ParaView
