/*
   ____    _ __           ____               __    ____
  / __/___(_) /  ___ ____/ __ \__ _____ ___ / /_  /  _/__  ____
 _\ \/ __/ / _ \/ -_) __/ /_/ / // / -_|_-</ __/ _/ // _ \/ __/
/___/\__/_/_.__/\__/_/  \___\_\_,_/\__/___/\__/ /___/_//_/\__(_)

Copyright 2012 SciberQuest Inc.
*/
#ifndef __pqSQTensorGlyph_h
#define __pqSQTensorGlyph_h

#include "pqAutoGeneratedObjectPanel.h"

class pqSQTensorGlyph : public pqAutoGeneratedObjectPanel
{
  Q_OBJECT
public:
  pqSQTensorGlyph(pqProxy *proxy, QWidget *p);
};

#endif
