// SPDX-FileCopyrightText: Copyright (c) Kitware Inc.
// SPDX-FileCopyrightText: Copyright (c) Sandia Corporation
// SPDX-License-Identifier: BSD-3-Clause

#ifndef pqWidgetsInit_h
#define pqWidgetsInit_h

#include "pqWidgetsModule.h"

/**
 * pqWidgetsInit() is for initializing QT resources. When pqWidgets is built
 * as a static library, linkers may drop out entire object
 * files such as files generated by rcc. Client apps can call to use Qt
 * resources outside PV.
 */

PQWIDGETS_EXPORT void pqWidgetsInit();

#endif
