/*=========================================================================

   Program: ParaView
   Module:    pqPVThresholdPanel.cxx

   Copyright (c) 2005-2008 Sandia Corporation, Kitware Inc.
   All rights reserved.

   ParaView is a free software; you can redistribute it and/or modify it
   under the terms of the ParaView license version 1.2.

   See License_v1.2.txt for the full ParaView license.
   A copy of this license can be obtained by contacting
   Kitware Inc.
   28 Corporate Drive
   Clifton Park, NY 12065
   USA

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHORS OR
CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

=========================================================================*/

#include "pqPVThresholdPanel.h"

#include <QComboBox>
#include <QString>
#include "pqDoubleRangeWidget.h"
#include "pqSMAdaptor.h"
#include "vtkSMProperty.h"
#include "vtkSMPropertyHelper.h"
#include "vtkSMProxy.h"
#include "ui_pqPVThresholdPanel.h"

#include "pqFieldSelectionAdaptor.h"

pqPVThresholdPanel::pqPVThresholdPanel(pqProxy* pxy, QWidget* p) :
  pqAutoGeneratedObjectPanel(pxy, p)
{
  QObject::connect(this->findChild<QComboBox*>("SelectInputScalars"),
    SIGNAL(activated(int)), this, SLOT(variableChanged()),
    Qt::QueuedConnection);

  // One time deal.
  this->variableChanged();
}

pqPVThresholdPanel::~pqPVThresholdPanel()
{
}

void pqPVThresholdPanel::variableChanged()
{

  pqFieldSelectionAdaptor* adaptor =
      this->findChild<pqFieldSelectionAdaptor*>("FieldSelectionAdaptor");

  if(adaptor)
    {
    if(adaptor->attributeMode().compare(QString("Point Data"),
                                        Qt::CaseInsensitive) == 0)
      {
      this->findChild<QComboBox*>("SelectSelectionMode")->setEnabled(1);
      }
    else
      {
      this->findChild<QComboBox*>("SelectSelectionMode")->setEnabled(0);
      }
    }
}
