NAME
  ParaView::RemotingViewsPython
LIBRARY_NAME
  vtkRemotingViewsPython
SPDX_LICENSE_IDENTIFIER
  BSD-3-CLAUSE
SPDX_COPYRIGHT_TEXT
  Copyright (c) Sandia Corporation, Kitware Inc.
CONDITION
  PARAVIEW_USE_PYTHON AND PARAVIEW_ENABLE_RENDERING
GROUPS
  PARAVIEW_CORE
KIT
  ParaView::ServerManagerKit
DEPENDS
  ParaView::RemotingViews
PRIVATE_DEPENDS
  ParaView::VTKExtensionsMisc
  ParaView::VTKExtensionsFiltersRendering
  VTK::CommonSystem
  VTK::PythonInterpreter
  VTK::WrappingPythonCore
