vtk_module(vtkPVServerManagerRendering
  GROUPS
    ParaViewRendering
  DEPENDS
    vtkPVServerManagerCore
    vtkPVServerImplementationRendering
  PRIVATE_DEPENDS
    vtksys
  TEST_LABELS
    PARAVIEW
)
