vtk_module(vtkStreaming
  DEPENDS
   vtkRenderingOpenGL
   vtkRenderingFreeTypeOpenGL
   vtkInteractionStyle
   vtkFiltersCore
   vtkIOCore
   vtkImagingSources
   vtkIONetCDF
   vtknetcdf
  TEST_DEPENDS
    vtkFiltersProgrammable
    vtkTestingRendering
  TEST_LABELS
    PARAVIEW
  EXCLUDE_FROM_WRAP_HIERARCHY
)
