# The PYQT external project

set(PYQT_binary "${CMAKE_CURRENT_BINARY_DIR}/PYQT/")

ExternalProject_Add(PyQt
  URL ${PYQT_URL}/${PYQT_GZ}
  DOWNLOAD_DIR ${CMAKE_CURRENT_BINARY_DIR}
  SOURCE_DIR ${CMAKE_CURRENT_BINARY_DIR}/PyQt
  BINARY_DIR ${CMAKE_CURRENT_BINARY_DIR}/PyQt
  BUILD_IN_SOURCE 1
  CONFIGURE_COMMAND ${PYTHON_EXECUTABLE} configure.py -q ${QT_QMAKE_EXECUTABLE}
  DEPENDS
    ${PYQT_dependencies}
  )
