# The LAPACK external project

set(lapack_source "${CMAKE_CURRENT_BINARY_DIR}/LAPACK")
set(lapack_binary "${CMAKE_CURRENT_BINARY_DIR}/LAPACK-build")
set(NUMPY_LAPACK_binary ${lapack_binary})

if(WIN32)
  set(LAPACK_EXTRA_ARGS 
    -DBUILD_STATIC_LIBS:BOOL=ON
    -DBUILD_SHARED_LIBS:BOOL=OFF
    )
else()
  set(LAPACK_EXTRA_ARGS 
    -DBUILD_STATIC_LIBS:BOOL=OFF
    -DBUILD_SHARED_LIBS:BOOL=ON
    )
endif()


ExternalProject_Add(LAPACK
  DOWNLOAD_DIR ${CMAKE_CURRENT_BINARY_DIR}
  SOURCE_DIR ${lapack_source}
  BINARY_DIR ${lapack_binary}
  URL ${LAPACK_URL}/${LAPACK_GZ}
  URL_MD5 ${LAPACK_MD5}
  CMAKE_ARGS
    -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
    -DBUILD_SHARED_LIBS:BOOL=OFF
    -DBUILD_STATIC_LIBS:BOOL=ON
    -DBUILD_TESTING:BOOL=OFF
  CMAKE_ARGS
      -DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>
  )
