# The SIP external project

set(SIP_binary "${CMAKE_CURRENT_BINARY_DIR}/SIP/")

ExternalProject_Add(SIP
  URL ${SIP_URL}/${SIP_GZ}
  DOWNLOAD_DIR ${CMAKE_CURRENT_BINARY_DIR}
  SOURCE_DIR ${CMAKE_CURRENT_BINARY_DIR}/SIP
  BINARY_DIR ${CMAKE_CURRENT_BINARY_DIR}/SIP
  BUILD_IN_SOURCE 1
  CONFIGURE_COMMAND ${PYTHON_EXECUTABLE} configure.py
  DEPENDS
    ${SIP_dependencies}
  )
