NAME
  ParaView::RemotingClientServerStream
LIBRARY_NAME
  vtkRemotingClientServerStream
SPDX_LICENSE_IDENTIFIER
  BSD-3-Clause
SPDX_COPYRIGHT_TEXT
  Copyright (c) Kitware Inc.
KIT
  ParaView::CoreKit
DESCRIPTION
  Client-server stream and interpreter and related classes
GROUPS
  PARAVIEW_CORE
DEPENDS
  VTK::CommonCore
PRIVATE_DEPENDS
  VTK::vtksys
TEST_DEPENDS
  VTK::CommonCore
  VTK::TestingCore
TEST_LABELS
  ParaView
