NAME
  BagPlotViewsAndFilters::BagPlotViewsAndFiltersBagPlot
LIBRARY_NAME
  vtkBagPlotViewsAndFiltersBagPlot
SPDX_LICENSE_IDENTIFIER
  BSD-3-CLAUSE
SPDX_COPYRIGHT_TEXT
  Copyright (c) Sandia Corporation, Kitware Inc.
DEPENDS
  ParaView::RemotingViews
  VTK::CommonExecutionModel
PRIVATE_DEPENDS
  ParaView::VTKExtensionsFiltersRendering
  ParaView::VTKExtensionsFiltersStatistics
  ParaView::VTKExtensionsMisc
  VTK::FiltersExtraction
  VTK::FiltersStatistics
  VTK::InfovisCore
