/*
   ____    _ __           ____               __    ____
  / __/___(_) /  ___ ____/ __ \__ _____ ___ / /_  /  _/__  ____
 _\ \/ __/ / _ \/ -_) __/ /_/ / // / -_|_-</ __/ _/ // _ \/ __/
/___/\__/_/_.__/\__/_/  \___\_\_,_/\__/___/\__/ /___/_//_/\__(_)

Copyright 2012 SciberQuest Inc.
*/
#ifndef __SQVTKTemplateMacroWarningSupression_h
#define __SQVTKTemplateMacroWarningSupression_h

#if defined(WIN32)
// quiet warnings generated by vtk template macro expansion
#pragma warning(disable : 4146) // unary minus applied to unsigned type
#pragma warning(disable : 4244) // coversion to smaller type
#endif

#endif

// VTK-HeaderTest-Exclude: SQVTKTemplateMacroWarningSupression.h
