NAME
  ParaView::AdaptorsParticle
LIBRARY_NAME
  vtkPVAdaptorsParticle
SPDX_LICENSE_IDENTIFIER
  BSD-3-Clause
SPDX_COPYRIGHT_TEXT
  Copyright (c) Kitware Inc.
GROUPS
  PARAVIEW_CANONICAL
CONDITION
  PARAVIEW_USE_MPI AND PARAVIEW_ENABLE_RENDERING
DEPENDS
  ParaView::Catalyst
  ParaView::RemotingViews
  VTK::CommonCore
  VTK::CommonDataModel
  VTK::IOImage
  VTK::IOParallelXML
  VTK::ParallelMPI
  VTK::RenderingCore
  VTK::RenderingOpenGL2
OPTIONAL_DEPENDS
  VTK::ParallelMPI
EXCLUDE_WRAP
