vtk_module(vtkPVServerManagerDefault
  DEPENDS
    vtkFiltersCosmo
    vtkFiltersFlowPaths
    vtkFiltersTexture
    vtkIOExport
    vtkIOImage
    vtkIONetCDF
    vtkIOParallelLSDyna
    vtkIOVPIC
    vtkPVServerImplementationDefault
    vtkPVServerManagerRendering
    vtkRenderingHybridOpenGL
    vtkTestingRendering
  TEST_DEPENDS
    vtkPVServerManagerApplication
)
