vtk_module(vtkPVServerManagerDefault
  GROUPS
    ParaView
  DEPENDS
    vtkPVServerManagerRendering
    vtkPVServerImplementationDefault
    vtkTestingRendering
    vtkIOExport
  TEST_DEPENDS
    vtkPVServerManagerApplication
)
