NAME
  HyperTreeGridFilters
LIBRARY_NAME
  vtkFiltersHyperTreeGridADR
SPDX_LICENSE_IDENTIFIER
  BSD-3-CLAUSE
SPDX_COPYRIGHT_TEXT
  Copyright (c) Sandia Corporation, Kitware Inc.
DESCRIPTION
  Hypertree filters and algorithms
GROUPS
  StandAlone
DEPENDS
  VTK::CommonDataModel
  VTK::CommonExecutionModel
  VTK::CommonMisc
  VTK::FiltersCore
  VTK::FiltersGeneral
  VTK::FiltersParallelDIY2
  VTK::ParallelCore
PRIVATE_DEPENDS
  VTK::CommonCore
  VTK::CommonSystem
