find_path(GRAPHVIZ_INCLUDE_DIR
  NAMES
    cgraph.h
  PATH_SUFFIXES
    graphviz
    )
mark_as_advanced(GRAPHVIZ_INCLUDE_DIR)

find_library(GRAPHVIZ_CDT_LIBRARY
  NAMES
    cdt
    )
mark_as_advanced(GRAPHVIZ_CDT_LIBRARY)

find_library(GRAPHVIZ_GVC_LIBRARY
  NAMES
    gvc
    )
mark_as_advanced(GRAPHVIZ_GVC_LIBRARY)

find_library(GRAPHVIZ_CGRAPH_LIBRARY
  NAMES
    cgraph
    )
mark_as_advanced(GRAPHVIZ_CGRAPH_LIBRARY)

find_library(GRAPHVIZ_PATHPLAN_LIBRARY
  NAMES
    pathplan
    )
mark_as_advanced(GRAPHVIZ_PATHPLAN_LIBRARY)

if(GRAPHVIZ_INCLUDE_DIR
  AND GRAPHVIZ_CDT_LIBRARY
  AND GRAPHVIZ_GVC_LIBRARY
  AND GRAPHVIZ_CGRAPH_LIBRARY
  AND GRAPHVIZ_PATHPLAN_LIBRARY
)
  set(GRAPHVIZ_FOUND TRUE)
else()
  set(GRAPHVIZ_FOUND FALSE)
endif()
