KWConvertImageToHeader --zlib --base64 \
    vtkKWWindowLayoutResources.h \
    KWWindowLayout1x1.png \
    KWWindowLayout1x1c.png \
    KWWindowLayout1x2.png \
    KWWindowLayout1x2c.png \
    KWWindowLayout2x1.png \
    KWWindowLayout2x1c.png \
    KWWindowLayout2x2.png \
    KWWindowLayout2x2c.png \
    KWWindowLayout2x3.png \
    KWWindowLayout2x3c.png \
    KWWindowLayout3x2.png \
    KWWindowLayout3x2c.png

KWConvertImageToHeader --zlib --base64 \
    vtkKWIconResources.h \
    annotate.png \
    axes.png \
    connection.png \
    contours.png \
    cut.png \
    doc_aif.png \
    doc_asf.png \
    doc_avi.png \
    doc_bmp.png \
    doc_chm.png \
    doc_exe.png \
    doc_gif.png \
    doc_hlp.png \
    doc_http.png \
    doc_jpg.png \
    doc_mp3.png \
    doc_mpeg.png \
    doc_msi.png \
    doc_pdf.png \
    doc_png.png \
    doc_postscript.png \
    doc_powerpoint.png \
    doc_quicktime.png \
    doc_realaudio.png \
    doc_tga.png \
    doc_tif.png \
    doc_txt.png \
    doc_wav.png \
    doc_word.png \
    doc_zip.png \
    error.png \
    expand.png \
    filters.png \
    folder.png \
    folder_open.png \
    general.png \
    grid_linear.png \
    grid_log.png \
    helpbubble.png \
    info_mini.png \
    layout.png \
    lock.png \
    macros.png \
    mag_glass.png \
    material.png \
    minus.png \
    move.png \
    move_h.png \
    move_v.png \
    plus.png \
    preferences.png \
    question.png \
    reload.png \
    shrink.png \
    smallerror.png \
    smallerrorred.png \
    stopwatch.png \
    transfer.png \
    transport_beginning.png \
    transport_end.png \
    transport_fast_forward.png \
    transport_fast_forward_to_key.png \
    transport_loop.png \
    transport_pause.png \
    transport_play.png \
    transport_play_to_key.png \
    transport_rewind.png \
    transport_rewind_to_key.png \
    transport_stop.png \
    trashcan.png \
    tree_close.png \
    tree_open.png \
    warning.png \
    warning_mini.png \
    window_level.png
