'\"
'\" Copyright (c) 1998-2000 by Scriptics Corporation.
'\" All rights reserved.
'\" 
'\" RCS: @(#) Id
'\" 
.so man.macros
.TH Tk_GetHISTANCE 3 "" Tk "Tk Library Procedures"
.BS
.SH NAME
Tk_GetHINSTANCE \- retrieve the global application instance handle
.SH SYNOPSIS
.nf
\fB#include <tk.h>\fR
.sp
HINSTANCE
\fBTk_GetHINSTANCE\fR()
.BE

.SH DESCRIPTION
.PP
\fBTk_GetHINSTANCE\fR returns the Windows application instance handle
for the Tk application.  This function is only available on Windows platforms.

.SH KEYWORDS
identifier, instance
