#!/bin/sh
# This script is invoked when installing manual entries.  It generates
# additional links to manual entries, corresponding to the procedure
# and command names described by the manual entry.  For example, the
# Tcl manual entry Hash.3 describes procedures Tcl_InitHashTable,
# Tcl_CreateHashEntry, and many more.  This script will make hard
# links so that Tcl_InitHashTable.3, Tcl_CreateHashEntry.3, and so
# on all refer to Hash.3 in the installed directory.
#
# Because of the length of command and procedure names, this mechanism
# only works on machines that support file names longer than 14 characters.
# This script checks to see if long file names are supported, and it
# doesn't make any links if they are not.
#
# The script takes one argument, which is the name of the directory
# where the manual entries have been installed.

ZIP=true
while true; do
    case $1 in
        -s | --symlinks )
            S=-s
            ;;
        -z | --compress )
            ZIP=$2
            shift
            ;;
        *) break
            ;;
    esac
    shift
done

if test $# != 1; then
    echo "Usage: mkLinks <options> dir"
    exit 1
fi

if test "x$ZIP" != "xtrue"; then
    touch TeST
    $ZIP TeST
    Z=`ls TeST* | sed 's/^[^.]*//'`
    rm -f TeST*
fi

cd $1
echo foo > xyzzyTestingAVeryLongFileName.foo
x=`echo xyzzyTe*`
echo foo > xyzzyTestingaverylongfilename.foo
y=`echo xyzzyTestingav*`
rm xyzzyTe*
if test "$x" != "xyzzyTestingAVeryLongFileName.foo"; then
    exit
fi
if test "$y" != "xyzzyTestingaverylongfilename.foo"; then
    CASEINSENSITIVEFS=1
fi

if test -r 3DBorder.3; then
    rm -f 3DBorder.3.*
    $ZIP 3DBorder.3
    rm -f Tk_Alloc3DBorderFromObj.3 Tk_Alloc3DBorderFromObj.3.* 
    rm -f Tk_Get3DBorder.3 Tk_Get3DBorder.3.* 
    rm -f Tk_Get3DBorderFromObj.3 Tk_Get3DBorderFromObj.3.* 
    rm -f Tk_Draw3DRectangle.3 Tk_Draw3DRectangle.3.* 
    rm -f Tk_Fill3DRectangle.3 Tk_Fill3DRectangle.3.* 
    rm -f Tk_Draw3DPolygon.3 Tk_Draw3DPolygon.3.* 
    rm -f Tk_Fill3DPolygon.3 Tk_Fill3DPolygon.3.* 
    rm -f Tk_3DVerticalBevel.3 Tk_3DVerticalBevel.3.* 
    rm -f Tk_3DHorizontalBevel.3 Tk_3DHorizontalBevel.3.* 
    rm -f Tk_SetBackgroundFromBorder.3 Tk_SetBackgroundFromBorder.3.* 
    rm -f Tk_NameOf3DBorder.3 Tk_NameOf3DBorder.3.* 
    rm -f Tk_3DBorderColor.3 Tk_3DBorderColor.3.* 
    rm -f Tk_3DBorderGC.3 Tk_3DBorderGC.3.* 
    rm -f Tk_Free3DBorderFromObj.3 Tk_Free3DBorderFromObj.3.* 
    rm -f Tk_Free3DBorder.3 Tk_Free3DBorder.3.* 
    ln $S 3DBorder.3$Z Tk_Alloc3DBorderFromObj.3$Z 
    ln $S 3DBorder.3$Z Tk_Get3DBorder.3$Z 
    ln $S 3DBorder.3$Z Tk_Get3DBorderFromObj.3$Z 
    ln $S 3DBorder.3$Z Tk_Draw3DRectangle.3$Z 
    ln $S 3DBorder.3$Z Tk_Fill3DRectangle.3$Z 
    ln $S 3DBorder.3$Z Tk_Draw3DPolygon.3$Z 
    ln $S 3DBorder.3$Z Tk_Fill3DPolygon.3$Z 
    ln $S 3DBorder.3$Z Tk_3DVerticalBevel.3$Z 
    ln $S 3DBorder.3$Z Tk_3DHorizontalBevel.3$Z 
    ln $S 3DBorder.3$Z Tk_SetBackgroundFromBorder.3$Z 
    ln $S 3DBorder.3$Z Tk_NameOf3DBorder.3$Z 
    ln $S 3DBorder.3$Z Tk_3DBorderColor.3$Z 
    ln $S 3DBorder.3$Z Tk_3DBorderGC.3$Z 
    ln $S 3DBorder.3$Z Tk_Free3DBorderFromObj.3$Z 
    ln $S 3DBorder.3$Z Tk_Free3DBorder.3$Z 
fi
if test -r AddOption.3; then
    rm -f AddOption.3.*
    $ZIP AddOption.3
    rm -f Tk_AddOption.3 Tk_AddOption.3.* 
    ln $S AddOption.3$Z Tk_AddOption.3$Z 
fi
if test -r BindTable.3; then
    rm -f BindTable.3.*
    $ZIP BindTable.3
    rm -f Tk_CreateBindingTable.3 Tk_CreateBindingTable.3.* 
    rm -f Tk_DeleteBindingTable.3 Tk_DeleteBindingTable.3.* 
    rm -f Tk_CreateBinding.3 Tk_CreateBinding.3.* 
    rm -f Tk_DeleteBinding.3 Tk_DeleteBinding.3.* 
    rm -f Tk_GetBinding.3 Tk_GetBinding.3.* 
    rm -f Tk_GetAllBindings.3 Tk_GetAllBindings.3.* 
    rm -f Tk_DeleteAllBindings.3 Tk_DeleteAllBindings.3.* 
    rm -f Tk_BindEvent.3 Tk_BindEvent.3.* 
    ln $S BindTable.3$Z Tk_CreateBindingTable.3$Z 
    ln $S BindTable.3$Z Tk_DeleteBindingTable.3$Z 
    ln $S BindTable.3$Z Tk_CreateBinding.3$Z 
    ln $S BindTable.3$Z Tk_DeleteBinding.3$Z 
    ln $S BindTable.3$Z Tk_GetBinding.3$Z 
    ln $S BindTable.3$Z Tk_GetAllBindings.3$Z 
    ln $S BindTable.3$Z Tk_DeleteAllBindings.3$Z 
    ln $S BindTable.3$Z Tk_BindEvent.3$Z 
fi
if test -r CanvPsY.3; then
    rm -f CanvPsY.3.*
    $ZIP CanvPsY.3
    rm -f Tk_CanvasPsY.3 Tk_CanvasPsY.3.* 
    rm -f Tk_CanvasPsBitmap.3 Tk_CanvasPsBitmap.3.* 
    rm -f Tk_CanvasPsColor.3 Tk_CanvasPsColor.3.* 
    rm -f Tk_CanvasPsFont.3 Tk_CanvasPsFont.3.* 
    rm -f Tk_CanvasPsPath.3 Tk_CanvasPsPath.3.* 
    rm -f Tk_CanvasPsStipple.3 Tk_CanvasPsStipple.3.* 
    ln $S CanvPsY.3$Z Tk_CanvasPsY.3$Z 
    ln $S CanvPsY.3$Z Tk_CanvasPsBitmap.3$Z 
    ln $S CanvPsY.3$Z Tk_CanvasPsColor.3$Z 
    ln $S CanvPsY.3$Z Tk_CanvasPsFont.3$Z 
    ln $S CanvPsY.3$Z Tk_CanvasPsPath.3$Z 
    ln $S CanvPsY.3$Z Tk_CanvasPsStipple.3$Z 
fi
if test -r CanvTkwin.3; then
    rm -f CanvTkwin.3.*
    $ZIP CanvTkwin.3
    rm -f Tk_CanvasTkwin.3 Tk_CanvasTkwin.3.* 
    rm -f Tk_CanvasGetCoord.3 Tk_CanvasGetCoord.3.* 
    rm -f Tk_CanvasDrawableCoords.3 Tk_CanvasDrawableCoords.3.* 
    rm -f Tk_CanvasSetStippleOrigin.3 Tk_CanvasSetStippleOrigin.3.* 
    rm -f Tk_CanvasWindowCoords.3 Tk_CanvasWindowCoords.3.* 
    rm -f Tk_CanvasEventuallyRedraw.3 Tk_CanvasEventuallyRedraw.3.* 
    rm -f Tk_CanvasTagsOption.3 Tk_CanvasTagsOption.3.* 
    ln $S CanvTkwin.3$Z Tk_CanvasTkwin.3$Z 
    ln $S CanvTkwin.3$Z Tk_CanvasGetCoord.3$Z 
    ln $S CanvTkwin.3$Z Tk_CanvasDrawableCoords.3$Z 
    ln $S CanvTkwin.3$Z Tk_CanvasSetStippleOrigin.3$Z 
    ln $S CanvTkwin.3$Z Tk_CanvasWindowCoords.3$Z 
    ln $S CanvTkwin.3$Z Tk_CanvasEventuallyRedraw.3$Z 
    ln $S CanvTkwin.3$Z Tk_CanvasTagsOption.3$Z 
fi
if test -r CanvTxtInfo.3; then
    rm -f CanvTxtInfo.3.*
    $ZIP CanvTxtInfo.3
    rm -f Tk_CanvasTextInfo.3 Tk_CanvasTextInfo.3.* 
    ln $S CanvTxtInfo.3$Z Tk_CanvasTextInfo.3$Z 
fi
if test -r Clipboard.3; then
    rm -f Clipboard.3.*
    $ZIP Clipboard.3
    rm -f Tk_ClipboardClear.3 Tk_ClipboardClear.3.* 
    rm -f Tk_ClipboardAppend.3 Tk_ClipboardAppend.3.* 
    ln $S Clipboard.3$Z Tk_ClipboardClear.3$Z 
    ln $S Clipboard.3$Z Tk_ClipboardAppend.3$Z 
fi
if test -r ClrSelect.3; then
    rm -f ClrSelect.3.*
    $ZIP ClrSelect.3
    rm -f Tk_ClearSelection.3 Tk_ClearSelection.3.* 
    ln $S ClrSelect.3$Z Tk_ClearSelection.3$Z 
fi
if test -r ConfigWidg.3; then
    rm -f ConfigWidg.3.*
    $ZIP ConfigWidg.3
    rm -f Tk_ConfigureWidget.3 Tk_ConfigureWidget.3.* 
    rm -f Tk_ConfigureInfo.3 Tk_ConfigureInfo.3.* 
    rm -f Tk_ConfigureValue.3 Tk_ConfigureValue.3.* 
    rm -f Tk_FreeOptions.3 Tk_FreeOptions.3.* 
    ln $S ConfigWidg.3$Z Tk_ConfigureWidget.3$Z 
    ln $S ConfigWidg.3$Z Tk_ConfigureInfo.3$Z 
    ln $S ConfigWidg.3$Z Tk_ConfigureValue.3$Z 
    ln $S ConfigWidg.3$Z Tk_FreeOptions.3$Z 
fi
if test -r ConfigWind.3; then
    rm -f ConfigWind.3.*
    $ZIP ConfigWind.3
    rm -f Tk_ConfigureWindow.3 Tk_ConfigureWindow.3.* 
    rm -f Tk_MoveWindow.3 Tk_MoveWindow.3.* 
    rm -f Tk_ResizeWindow.3 Tk_ResizeWindow.3.* 
    rm -f Tk_MoveResizeWindow.3 Tk_MoveResizeWindow.3.* 
    rm -f Tk_SetWindowBorderWidth.3 Tk_SetWindowBorderWidth.3.* 
    rm -f Tk_ChangeWindowAttributes.3 Tk_ChangeWindowAttributes.3.* 
    rm -f Tk_SetWindowBackground.3 Tk_SetWindowBackground.3.* 
    rm -f Tk_SetWindowBackgroundPixmap.3 Tk_SetWindowBackgroundPixmap.3.* 
    rm -f Tk_SetWindowBorder.3 Tk_SetWindowBorder.3.* 
    rm -f Tk_SetWindowBorderPixmap.3 Tk_SetWindowBorderPixmap.3.* 
    rm -f Tk_SetWindowColormap.3 Tk_SetWindowColormap.3.* 
    rm -f Tk_DefineCursor.3 Tk_DefineCursor.3.* 
    rm -f Tk_UndefineCursor.3 Tk_UndefineCursor.3.* 
    ln $S ConfigWind.3$Z Tk_ConfigureWindow.3$Z 
    ln $S ConfigWind.3$Z Tk_MoveWindow.3$Z 
    ln $S ConfigWind.3$Z Tk_ResizeWindow.3$Z 
    ln $S ConfigWind.3$Z Tk_MoveResizeWindow.3$Z 
    ln $S ConfigWind.3$Z Tk_SetWindowBorderWidth.3$Z 
    ln $S ConfigWind.3$Z Tk_ChangeWindowAttributes.3$Z 
    ln $S ConfigWind.3$Z Tk_SetWindowBackground.3$Z 
    ln $S ConfigWind.3$Z Tk_SetWindowBackgroundPixmap.3$Z 
    ln $S ConfigWind.3$Z Tk_SetWindowBorder.3$Z 
    ln $S ConfigWind.3$Z Tk_SetWindowBorderPixmap.3$Z 
    ln $S ConfigWind.3$Z Tk_SetWindowColormap.3$Z 
    ln $S ConfigWind.3$Z Tk_DefineCursor.3$Z 
    ln $S ConfigWind.3$Z Tk_UndefineCursor.3$Z 
fi
if test -r CoordToWin.3; then
    rm -f CoordToWin.3.*
    $ZIP CoordToWin.3
    rm -f Tk_CoordsToWindow.3 Tk_CoordsToWindow.3.* 
    ln $S CoordToWin.3$Z Tk_CoordsToWindow.3$Z 
fi
if test -r CrtCmHdlr.3; then
    rm -f CrtCmHdlr.3.*
    $ZIP CrtCmHdlr.3
    rm -f Tk_CreateClientMessageHandler.3 Tk_CreateClientMessageHandler.3.* 
    rm -f Tk_DeleteClientMessageHandler.3 Tk_DeleteClientMessageHandler.3.* 
    ln $S CrtCmHdlr.3$Z Tk_CreateClientMessageHandler.3$Z 
    ln $S CrtCmHdlr.3$Z Tk_DeleteClientMessageHandler.3$Z 
fi
if test -r CrtErrHdlr.3; then
    rm -f CrtErrHdlr.3.*
    $ZIP CrtErrHdlr.3
    rm -f Tk_CreateErrorHandler.3 Tk_CreateErrorHandler.3.* 
    rm -f Tk_DeleteErrorHandler.3 Tk_DeleteErrorHandler.3.* 
    ln $S CrtErrHdlr.3$Z Tk_CreateErrorHandler.3$Z 
    ln $S CrtErrHdlr.3$Z Tk_DeleteErrorHandler.3$Z 
fi
if test -r CrtGenHdlr.3; then
    rm -f CrtGenHdlr.3.*
    $ZIP CrtGenHdlr.3
    rm -f Tk_CreateGenericHandler.3 Tk_CreateGenericHandler.3.* 
    rm -f Tk_DeleteGenericHandler.3 Tk_DeleteGenericHandler.3.* 
    ln $S CrtGenHdlr.3$Z Tk_CreateGenericHandler.3$Z 
    ln $S CrtGenHdlr.3$Z Tk_DeleteGenericHandler.3$Z 
fi
if test -r CrtImgType.3; then
    rm -f CrtImgType.3.*
    $ZIP CrtImgType.3
    rm -f Tk_CreateImageType.3 Tk_CreateImageType.3.* 
    rm -f Tk_GetImageMasterData.3 Tk_GetImageMasterData.3.* 
    rm -f Tk_InitImageArgs.3 Tk_InitImageArgs.3.* 
    ln $S CrtImgType.3$Z Tk_CreateImageType.3$Z 
    ln $S CrtImgType.3$Z Tk_GetImageMasterData.3$Z 
    ln $S CrtImgType.3$Z Tk_InitImageArgs.3$Z 
fi
if test -r CrtItemType.3; then
    rm -f CrtItemType.3.*
    $ZIP CrtItemType.3
    rm -f Tk_CreateItemType.3 Tk_CreateItemType.3.* 
    rm -f Tk_GetItemTypes.3 Tk_GetItemTypes.3.* 
    ln $S CrtItemType.3$Z Tk_CreateItemType.3$Z 
    ln $S CrtItemType.3$Z Tk_GetItemTypes.3$Z 
fi
if test -r CrtPhImgFmt.3; then
    rm -f CrtPhImgFmt.3.*
    $ZIP CrtPhImgFmt.3
    rm -f Tk_CreatePhotoImageFormat.3 Tk_CreatePhotoImageFormat.3.* 
    ln $S CrtPhImgFmt.3$Z Tk_CreatePhotoImageFormat.3$Z 
fi
if test -r CrtSelHdlr.3; then
    rm -f CrtSelHdlr.3.*
    $ZIP CrtSelHdlr.3
    rm -f Tk_CreateSelHandler.3 Tk_CreateSelHandler.3.* 
    rm -f Tk_DeleteSelHandler.3 Tk_DeleteSelHandler.3.* 
    ln $S CrtSelHdlr.3$Z Tk_CreateSelHandler.3$Z 
    ln $S CrtSelHdlr.3$Z Tk_DeleteSelHandler.3$Z 
fi
if test -r CrtWindow.3; then
    rm -f CrtWindow.3.*
    $ZIP CrtWindow.3
    rm -f Tk_CreateWindow.3 Tk_CreateWindow.3.* 
    rm -f Tk_CreateWindowFromPath.3 Tk_CreateWindowFromPath.3.* 
    rm -f Tk_DestroyWindow.3 Tk_DestroyWindow.3.* 
    rm -f Tk_MakeWindowExist.3 Tk_MakeWindowExist.3.* 
    ln $S CrtWindow.3$Z Tk_CreateWindow.3$Z 
    ln $S CrtWindow.3$Z Tk_CreateWindowFromPath.3$Z 
    ln $S CrtWindow.3$Z Tk_DestroyWindow.3$Z 
    ln $S CrtWindow.3$Z Tk_MakeWindowExist.3$Z 
fi
if test -r DeleteImg.3; then
    rm -f DeleteImg.3.*
    $ZIP DeleteImg.3
    rm -f Tk_DeleteImage.3 Tk_DeleteImage.3.* 
    ln $S DeleteImg.3$Z Tk_DeleteImage.3$Z 
fi
if test -r DrawFocHlt.3; then
    rm -f DrawFocHlt.3.*
    $ZIP DrawFocHlt.3
    rm -f Tk_DrawFocusHighlight.3 Tk_DrawFocusHighlight.3.* 
    ln $S DrawFocHlt.3$Z Tk_DrawFocusHighlight.3$Z 
fi
if test -r EventHndlr.3; then
    rm -f EventHndlr.3.*
    $ZIP EventHndlr.3
    rm -f Tk_CreateEventHandler.3 Tk_CreateEventHandler.3.* 
    rm -f Tk_DeleteEventHandler.3 Tk_DeleteEventHandler.3.* 
    ln $S EventHndlr.3$Z Tk_CreateEventHandler.3$Z 
    ln $S EventHndlr.3$Z Tk_DeleteEventHandler.3$Z 
fi
if test -r FindPhoto.3; then
    rm -f FindPhoto.3.*
    $ZIP FindPhoto.3
    rm -f Tk_FindPhoto.3 Tk_FindPhoto.3.* 
    rm -f Tk_PhotoPutBlock.3 Tk_PhotoPutBlock.3.* 
    rm -f Tk_PhotoPutZoomedBlock.3 Tk_PhotoPutZoomedBlock.3.* 
    rm -f Tk_PhotoGetImage.3 Tk_PhotoGetImage.3.* 
    rm -f Tk_PhotoBlank.3 Tk_PhotoBlank.3.* 
    rm -f Tk_PhotoExpand.3 Tk_PhotoExpand.3.* 
    rm -f Tk_PhotoGetSize.3 Tk_PhotoGetSize.3.* 
    rm -f Tk_PhotoSetSize.3 Tk_PhotoSetSize.3.* 
    ln $S FindPhoto.3$Z Tk_FindPhoto.3$Z 
    ln $S FindPhoto.3$Z Tk_PhotoPutBlock.3$Z 
    ln $S FindPhoto.3$Z Tk_PhotoPutZoomedBlock.3$Z 
    ln $S FindPhoto.3$Z Tk_PhotoGetImage.3$Z 
    ln $S FindPhoto.3$Z Tk_PhotoBlank.3$Z 
    ln $S FindPhoto.3$Z Tk_PhotoExpand.3$Z 
    ln $S FindPhoto.3$Z Tk_PhotoGetSize.3$Z 
    ln $S FindPhoto.3$Z Tk_PhotoSetSize.3$Z 
fi
if test -r FontId.3; then
    rm -f FontId.3.*
    $ZIP FontId.3
    rm -f Tk_FontId.3 Tk_FontId.3.* 
    rm -f Tk_GetFontMetrics.3 Tk_GetFontMetrics.3.* 
    rm -f Tk_PostscriptFontName.3 Tk_PostscriptFontName.3.* 
    ln $S FontId.3$Z Tk_FontId.3$Z 
    ln $S FontId.3$Z Tk_GetFontMetrics.3$Z 
    ln $S FontId.3$Z Tk_PostscriptFontName.3$Z 
fi
if test -r FreeXId.3; then
    rm -f FreeXId.3.*
    $ZIP FreeXId.3
    rm -f Tk_FreeXId.3 Tk_FreeXId.3.* 
    ln $S FreeXId.3$Z Tk_FreeXId.3$Z 
fi
if test -r GeomReq.3; then
    rm -f GeomReq.3.*
    $ZIP GeomReq.3
    rm -f Tk_GeometryRequest.3 Tk_GeometryRequest.3.* 
    rm -f Tk_SetMinimumRequestSize.3 Tk_SetMinimumRequestSize.3.* 
    rm -f Tk_SetInternalBorder.3 Tk_SetInternalBorder.3.* 
    rm -f Tk_SetInternalBorderEx.3 Tk_SetInternalBorderEx.3.* 
    ln $S GeomReq.3$Z Tk_GeometryRequest.3$Z 
    ln $S GeomReq.3$Z Tk_SetMinimumRequestSize.3$Z 
    ln $S GeomReq.3$Z Tk_SetInternalBorder.3$Z 
    ln $S GeomReq.3$Z Tk_SetInternalBorderEx.3$Z 
fi
if test -r GetAnchor.3; then
    rm -f GetAnchor.3.*
    $ZIP GetAnchor.3
    rm -f Tk_GetAnchorFromObj.3 Tk_GetAnchorFromObj.3.* 
    rm -f Tk_GetAnchor.3 Tk_GetAnchor.3.* 
    rm -f Tk_NameOfAnchor.3 Tk_NameOfAnchor.3.* 
    ln $S GetAnchor.3$Z Tk_GetAnchorFromObj.3$Z 
    ln $S GetAnchor.3$Z Tk_GetAnchor.3$Z 
    ln $S GetAnchor.3$Z Tk_NameOfAnchor.3$Z 
fi
if test -r GetBitmap.3; then
    rm -f GetBitmap.3.*
    $ZIP GetBitmap.3
    rm -f Tk_AllocBitmapFromObj.3 Tk_AllocBitmapFromObj.3.* 
    rm -f Tk_GetBitmap.3 Tk_GetBitmap.3.* 
    rm -f Tk_GetBitmapFromObj.3 Tk_GetBitmapFromObj.3.* 
    rm -f Tk_DefineBitmap.3 Tk_DefineBitmap.3.* 
    rm -f Tk_NameOfBitmap.3 Tk_NameOfBitmap.3.* 
    rm -f Tk_SizeOfBitmap.3 Tk_SizeOfBitmap.3.* 
    rm -f Tk_FreeBitmapFromObj.3 Tk_FreeBitmapFromObj.3.* 
    rm -f Tk_FreeBitmap.3 Tk_FreeBitmap.3.* 
    ln $S GetBitmap.3$Z Tk_AllocBitmapFromObj.3$Z 
    ln $S GetBitmap.3$Z Tk_GetBitmap.3$Z 
    ln $S GetBitmap.3$Z Tk_GetBitmapFromObj.3$Z 
    ln $S GetBitmap.3$Z Tk_DefineBitmap.3$Z 
    ln $S GetBitmap.3$Z Tk_NameOfBitmap.3$Z 
    ln $S GetBitmap.3$Z Tk_SizeOfBitmap.3$Z 
    ln $S GetBitmap.3$Z Tk_FreeBitmapFromObj.3$Z 
    ln $S GetBitmap.3$Z Tk_FreeBitmap.3$Z 
fi
if test -r GetCapStyl.3; then
    rm -f GetCapStyl.3.*
    $ZIP GetCapStyl.3
    rm -f Tk_GetCapStyle.3 Tk_GetCapStyle.3.* 
    rm -f Tk_NameOfCapStyle.3 Tk_NameOfCapStyle.3.* 
    ln $S GetCapStyl.3$Z Tk_GetCapStyle.3$Z 
    ln $S GetCapStyl.3$Z Tk_NameOfCapStyle.3$Z 
fi
if test -r GetClrmap.3; then
    rm -f GetClrmap.3.*
    $ZIP GetClrmap.3
    rm -f Tk_GetColormap.3 Tk_GetColormap.3.* 
    rm -f Tk_FreeColormap.3 Tk_FreeColormap.3.* 
    ln $S GetClrmap.3$Z Tk_GetColormap.3$Z 
    ln $S GetClrmap.3$Z Tk_FreeColormap.3$Z 
fi
if test -r GetColor.3; then
    rm -f GetColor.3.*
    $ZIP GetColor.3
    rm -f Tk_AllocColorFromObj.3 Tk_AllocColorFromObj.3.* 
    rm -f Tk_GetColor.3 Tk_GetColor.3.* 
    rm -f Tk_GetColorFromObj.3 Tk_GetColorFromObj.3.* 
    rm -f Tk_GetColorByValue.3 Tk_GetColorByValue.3.* 
    rm -f Tk_NameOfColor.3 Tk_NameOfColor.3.* 
    rm -f Tk_FreeColorFromObj.3 Tk_FreeColorFromObj.3.* 
    rm -f Tk_FreeColor.3 Tk_FreeColor.3.* 
    ln $S GetColor.3$Z Tk_AllocColorFromObj.3$Z 
    ln $S GetColor.3$Z Tk_GetColor.3$Z 
    ln $S GetColor.3$Z Tk_GetColorFromObj.3$Z 
    ln $S GetColor.3$Z Tk_GetColorByValue.3$Z 
    ln $S GetColor.3$Z Tk_NameOfColor.3$Z 
    ln $S GetColor.3$Z Tk_FreeColorFromObj.3$Z 
    ln $S GetColor.3$Z Tk_FreeColor.3$Z 
fi
if test -r GetCursor.3; then
    rm -f GetCursor.3.*
    $ZIP GetCursor.3
    rm -f Tk_AllocCursorFromObj.3 Tk_AllocCursorFromObj.3.* 
    rm -f Tk_GetCursor.3 Tk_GetCursor.3.* 
    rm -f Tk_GetCursorFromObj.3 Tk_GetCursorFromObj.3.* 
    rm -f Tk_GetCursorFromData.3 Tk_GetCursorFromData.3.* 
    rm -f Tk_NameOfCursor.3 Tk_NameOfCursor.3.* 
    rm -f Tk_FreeCursorFromObj.3 Tk_FreeCursorFromObj.3.* 
    rm -f Tk_FreeCursor.3 Tk_FreeCursor.3.* 
    ln $S GetCursor.3$Z Tk_AllocCursorFromObj.3$Z 
    ln $S GetCursor.3$Z Tk_GetCursor.3$Z 
    ln $S GetCursor.3$Z Tk_GetCursorFromObj.3$Z 
    ln $S GetCursor.3$Z Tk_GetCursorFromData.3$Z 
    ln $S GetCursor.3$Z Tk_NameOfCursor.3$Z 
    ln $S GetCursor.3$Z Tk_FreeCursorFromObj.3$Z 
    ln $S GetCursor.3$Z Tk_FreeCursor.3$Z 
fi
if test -r GetDash.3; then
    rm -f GetDash.3.*
    $ZIP GetDash.3
    rm -f Tk_GetDash.3 Tk_GetDash.3.* 
    ln $S GetDash.3$Z Tk_GetDash.3$Z 
fi
if test -r GetFont.3; then
    rm -f GetFont.3.*
    $ZIP GetFont.3
    rm -f Tk_AllocFontFromObj.3 Tk_AllocFontFromObj.3.* 
    rm -f Tk_GetFont.3 Tk_GetFont.3.* 
    rm -f Tk_GetFontFromObj.3 Tk_GetFontFromObj.3.* 
    rm -f Tk_NameOfFont.3 Tk_NameOfFont.3.* 
    rm -f Tk_FreeFontFromObj.3 Tk_FreeFontFromObj.3.* 
    rm -f Tk_FreeFont.3 Tk_FreeFont.3.* 
    ln $S GetFont.3$Z Tk_AllocFontFromObj.3$Z 
    ln $S GetFont.3$Z Tk_GetFont.3$Z 
    ln $S GetFont.3$Z Tk_GetFontFromObj.3$Z 
    ln $S GetFont.3$Z Tk_NameOfFont.3$Z 
    ln $S GetFont.3$Z Tk_FreeFontFromObj.3$Z 
    ln $S GetFont.3$Z Tk_FreeFont.3$Z 
fi
if test -r GetGC.3; then
    rm -f GetGC.3.*
    $ZIP GetGC.3
    rm -f Tk_GetGC.3 Tk_GetGC.3.* 
    rm -f Tk_FreeGC.3 Tk_FreeGC.3.* 
    ln $S GetGC.3$Z Tk_GetGC.3$Z 
    ln $S GetGC.3$Z Tk_FreeGC.3$Z 
fi
if test -r GetHINSTANCE.3; then
    rm -f GetHINSTANCE.3.*
    $ZIP GetHINSTANCE.3
    rm -f Tk_GetHINSTANCE.3 Tk_GetHINSTANCE.3.* 
    ln $S GetHINSTANCE.3$Z Tk_GetHINSTANCE.3$Z 
fi
if test -r GetHWND.3; then
    rm -f GetHWND.3.*
    $ZIP GetHWND.3
    rm -f Tk_GetHWND.3 Tk_GetHWND.3.* 
    rm -f Tk_AttachHWND.3 Tk_AttachHWND.3.* 
    ln $S GetHWND.3$Z Tk_GetHWND.3$Z 
    ln $S GetHWND.3$Z Tk_AttachHWND.3$Z 
fi
if test -r GetImage.3; then
    rm -f GetImage.3.*
    $ZIP GetImage.3
    rm -f Tk_GetImage.3 Tk_GetImage.3.* 
    rm -f Tk_RedrawImage.3 Tk_RedrawImage.3.* 
    rm -f Tk_SizeOfImage.3 Tk_SizeOfImage.3.* 
    rm -f Tk_FreeImage.3 Tk_FreeImage.3.* 
    ln $S GetImage.3$Z Tk_GetImage.3$Z 
    ln $S GetImage.3$Z Tk_RedrawImage.3$Z 
    ln $S GetImage.3$Z Tk_SizeOfImage.3$Z 
    ln $S GetImage.3$Z Tk_FreeImage.3$Z 
fi
if test -r GetJoinStl.3; then
    rm -f GetJoinStl.3.*
    $ZIP GetJoinStl.3
    rm -f Tk_GetJoinStyle.3 Tk_GetJoinStyle.3.* 
    rm -f Tk_NameOfJoinStyle.3 Tk_NameOfJoinStyle.3.* 
    ln $S GetJoinStl.3$Z Tk_GetJoinStyle.3$Z 
    ln $S GetJoinStl.3$Z Tk_NameOfJoinStyle.3$Z 
fi
if test -r GetJustify.3; then
    rm -f GetJustify.3.*
    $ZIP GetJustify.3
    rm -f Tk_GetJustifyFromObj.3 Tk_GetJustifyFromObj.3.* 
    rm -f Tk_GetJustify.3 Tk_GetJustify.3.* 
    rm -f Tk_NameOfJustify.3 Tk_NameOfJustify.3.* 
    ln $S GetJustify.3$Z Tk_GetJustifyFromObj.3$Z 
    ln $S GetJustify.3$Z Tk_GetJustify.3$Z 
    ln $S GetJustify.3$Z Tk_NameOfJustify.3$Z 
fi
if test -r GetOption.3; then
    rm -f GetOption.3.*
    $ZIP GetOption.3
    rm -f Tk_GetOption.3 Tk_GetOption.3.* 
    ln $S GetOption.3$Z Tk_GetOption.3$Z 
fi
if test -r GetPixels.3; then
    rm -f GetPixels.3.*
    $ZIP GetPixels.3
    rm -f Tk_GetPixelsFromObj.3 Tk_GetPixelsFromObj.3.* 
    rm -f Tk_GetPixels.3 Tk_GetPixels.3.* 
    rm -f Tk_GetMMFromObj.3 Tk_GetMMFromObj.3.* 
    rm -f Tk_GetScreenMM.3 Tk_GetScreenMM.3.* 
    ln $S GetPixels.3$Z Tk_GetPixelsFromObj.3$Z 
    ln $S GetPixels.3$Z Tk_GetPixels.3$Z 
    ln $S GetPixels.3$Z Tk_GetMMFromObj.3$Z 
    ln $S GetPixels.3$Z Tk_GetScreenMM.3$Z 
fi
if test -r GetPixmap.3; then
    rm -f GetPixmap.3.*
    $ZIP GetPixmap.3
    rm -f Tk_GetPixmap.3 Tk_GetPixmap.3.* 
    rm -f Tk_FreePixmap.3 Tk_FreePixmap.3.* 
    ln $S GetPixmap.3$Z Tk_GetPixmap.3$Z 
    ln $S GetPixmap.3$Z Tk_FreePixmap.3$Z 
fi
if test -r GetRelief.3; then
    rm -f GetRelief.3.*
    $ZIP GetRelief.3
    rm -f Tk_GetReliefFromObj.3 Tk_GetReliefFromObj.3.* 
    rm -f Tk_GetRelief.3 Tk_GetRelief.3.* 
    rm -f Tk_NameOfRelief.3 Tk_NameOfRelief.3.* 
    ln $S GetRelief.3$Z Tk_GetReliefFromObj.3$Z 
    ln $S GetRelief.3$Z Tk_GetRelief.3$Z 
    ln $S GetRelief.3$Z Tk_NameOfRelief.3$Z 
fi
if test -r GetRootCrd.3; then
    rm -f GetRootCrd.3.*
    $ZIP GetRootCrd.3
    rm -f Tk_GetRootCoords.3 Tk_GetRootCoords.3.* 
    ln $S GetRootCrd.3$Z Tk_GetRootCoords.3$Z 
fi
if test -r GetScroll.3; then
    rm -f GetScroll.3.*
    $ZIP GetScroll.3
    rm -f Tk_GetScrollInfo.3 Tk_GetScrollInfo.3.* 
    rm -f Tk_GetScrollInfoObj.3 Tk_GetScrollInfoObj.3.* 
    ln $S GetScroll.3$Z Tk_GetScrollInfo.3$Z 
    ln $S GetScroll.3$Z Tk_GetScrollInfoObj.3$Z 
fi
if test -r GetSelect.3; then
    rm -f GetSelect.3.*
    $ZIP GetSelect.3
    rm -f Tk_GetSelection.3 Tk_GetSelection.3.* 
    ln $S GetSelect.3$Z Tk_GetSelection.3$Z 
fi
if test -r GetUid.3; then
    rm -f GetUid.3.*
    $ZIP GetUid.3
    rm -f Tk_GetUid.3 Tk_GetUid.3.* 
    rm -f Tk_Uid.3 Tk_Uid.3.* 
    ln $S GetUid.3$Z Tk_GetUid.3$Z 
    ln $S GetUid.3$Z Tk_Uid.3$Z 
fi
if test -r GetVRoot.3; then
    rm -f GetVRoot.3.*
    $ZIP GetVRoot.3
    rm -f Tk_GetVRootGeometry.3 Tk_GetVRootGeometry.3.* 
    ln $S GetVRoot.3$Z Tk_GetVRootGeometry.3$Z 
fi
if test -r GetVisual.3; then
    rm -f GetVisual.3.*
    $ZIP GetVisual.3
    rm -f Tk_GetVisual.3 Tk_GetVisual.3.* 
    ln $S GetVisual.3$Z Tk_GetVisual.3$Z 
fi
if test -r Grab.3; then
    rm -f Grab.3.*
    $ZIP Grab.3
    rm -f Tk_Grab.3 Tk_Grab.3.* 
    rm -f Tk_Ungrab.3 Tk_Ungrab.3.* 
    ln $S Grab.3$Z Tk_Grab.3$Z 
    ln $S Grab.3$Z Tk_Ungrab.3$Z 
fi
if test -r HWNDToWindow.3; then
    rm -f HWNDToWindow.3.*
    $ZIP HWNDToWindow.3
    rm -f Tk_HWNDToWindow.3 Tk_HWNDToWindow.3.* 
    ln $S HWNDToWindow.3$Z Tk_HWNDToWindow.3$Z 
fi
if test -r HandleEvent.3; then
    rm -f HandleEvent.3.*
    $ZIP HandleEvent.3
    rm -f Tk_HandleEvent.3 Tk_HandleEvent.3.* 
    ln $S HandleEvent.3$Z Tk_HandleEvent.3$Z 
fi
if test -r IdToWindow.3; then
    rm -f IdToWindow.3.*
    $ZIP IdToWindow.3
    rm -f Tk_IdToWindow.3 Tk_IdToWindow.3.* 
    ln $S IdToWindow.3$Z Tk_IdToWindow.3$Z 
fi
if test -r ImgChanged.3; then
    rm -f ImgChanged.3.*
    $ZIP ImgChanged.3
    rm -f Tk_ImageChanged.3 Tk_ImageChanged.3.* 
    ln $S ImgChanged.3$Z Tk_ImageChanged.3$Z 
fi
if test -r InternAtom.3; then
    rm -f InternAtom.3.*
    $ZIP InternAtom.3
    rm -f Tk_InternAtom.3 Tk_InternAtom.3.* 
    rm -f Tk_GetAtomName.3 Tk_GetAtomName.3.* 
    ln $S InternAtom.3$Z Tk_InternAtom.3$Z 
    ln $S InternAtom.3$Z Tk_GetAtomName.3$Z 
fi
if test -r MainLoop.3; then
    rm -f MainLoop.3.*
    $ZIP MainLoop.3
    rm -f Tk_MainLoop.3 Tk_MainLoop.3.* 
    ln $S MainLoop.3$Z Tk_MainLoop.3$Z 
fi
if test -r MainWin.3; then
    rm -f MainWin.3.*
    $ZIP MainWin.3
    rm -f Tk_MainWindow.3 Tk_MainWindow.3.* 
    rm -f Tk_GetNumMainWindows.3 Tk_GetNumMainWindows.3.* 
    ln $S MainWin.3$Z Tk_MainWindow.3$Z 
    ln $S MainWin.3$Z Tk_GetNumMainWindows.3$Z 
fi
if test -r MaintGeom.3; then
    rm -f MaintGeom.3.*
    $ZIP MaintGeom.3
    rm -f Tk_MaintainGeometry.3 Tk_MaintainGeometry.3.* 
    rm -f Tk_UnmaintainGeometry.3 Tk_UnmaintainGeometry.3.* 
    ln $S MaintGeom.3$Z Tk_MaintainGeometry.3$Z 
    ln $S MaintGeom.3$Z Tk_UnmaintainGeometry.3$Z 
fi
if test -r ManageGeom.3; then
    rm -f ManageGeom.3.*
    $ZIP ManageGeom.3
    rm -f Tk_ManageGeometry.3 Tk_ManageGeometry.3.* 
    ln $S ManageGeom.3$Z Tk_ManageGeometry.3$Z 
fi
if test -r MapWindow.3; then
    rm -f MapWindow.3.*
    $ZIP MapWindow.3
    rm -f Tk_MapWindow.3 Tk_MapWindow.3.* 
    rm -f Tk_UnmapWindow.3 Tk_UnmapWindow.3.* 
    ln $S MapWindow.3$Z Tk_MapWindow.3$Z 
    ln $S MapWindow.3$Z Tk_UnmapWindow.3$Z 
fi
if test -r MeasureChar.3; then
    rm -f MeasureChar.3.*
    $ZIP MeasureChar.3
    rm -f Tk_MeasureChars.3 Tk_MeasureChars.3.* 
    rm -f Tk_TextWidth.3 Tk_TextWidth.3.* 
    rm -f Tk_DrawChars.3 Tk_DrawChars.3.* 
    rm -f Tk_UnderlineChars.3 Tk_UnderlineChars.3.* 
    ln $S MeasureChar.3$Z Tk_MeasureChars.3$Z 
    ln $S MeasureChar.3$Z Tk_TextWidth.3$Z 
    ln $S MeasureChar.3$Z Tk_DrawChars.3$Z 
    ln $S MeasureChar.3$Z Tk_UnderlineChars.3$Z 
fi
if test -r MoveToplev.3; then
    rm -f MoveToplev.3.*
    $ZIP MoveToplev.3
    rm -f Tk_MoveToplevelWindow.3 Tk_MoveToplevelWindow.3.* 
    ln $S MoveToplev.3$Z Tk_MoveToplevelWindow.3$Z 
fi
if test -r Name.3; then
    rm -f Name.3.*
    $ZIP Name.3
    rm -f Tk_Name.3 Tk_Name.3.* 
    rm -f Tk_PathName.3 Tk_PathName.3.* 
    rm -f Tk_NameToWindow.3 Tk_NameToWindow.3.* 
    ln $S Name.3$Z Tk_Name.3$Z 
    ln $S Name.3$Z Tk_PathName.3$Z 
    ln $S Name.3$Z Tk_NameToWindow.3$Z 
fi
if test -r NameOfImg.3; then
    rm -f NameOfImg.3.*
    $ZIP NameOfImg.3
    rm -f Tk_NameOfImage.3 Tk_NameOfImage.3.* 
    ln $S NameOfImg.3$Z Tk_NameOfImage.3$Z 
fi
if test -r OwnSelect.3; then
    rm -f OwnSelect.3.*
    $ZIP OwnSelect.3
    rm -f Tk_OwnSelection.3 Tk_OwnSelection.3.* 
    ln $S OwnSelect.3$Z Tk_OwnSelection.3$Z 
fi
if test -r ParseArgv.3; then
    rm -f ParseArgv.3.*
    $ZIP ParseArgv.3
    rm -f Tk_ParseArgv.3 Tk_ParseArgv.3.* 
    ln $S ParseArgv.3$Z Tk_ParseArgv.3$Z 
fi
if test -r QWinEvent.3; then
    rm -f QWinEvent.3.*
    $ZIP QWinEvent.3
    rm -f Tk_CollapseMotionEvents.3 Tk_CollapseMotionEvents.3.* 
    rm -f Tk_QueueWindowEvent.3 Tk_QueueWindowEvent.3.* 
    ln $S QWinEvent.3$Z Tk_CollapseMotionEvents.3$Z 
    ln $S QWinEvent.3$Z Tk_QueueWindowEvent.3$Z 
fi
if test -r Restack.3; then
    rm -f Restack.3.*
    $ZIP Restack.3
    rm -f Tk_RestackWindow.3 Tk_RestackWindow.3.* 
    ln $S Restack.3$Z Tk_RestackWindow.3$Z 
fi
if test -r RestrictEv.3; then
    rm -f RestrictEv.3.*
    $ZIP RestrictEv.3
    rm -f Tk_RestrictEvents.3 Tk_RestrictEvents.3.* 
    ln $S RestrictEv.3$Z Tk_RestrictEvents.3$Z 
fi
if test -r SetAppName.3; then
    rm -f SetAppName.3.*
    $ZIP SetAppName.3
    rm -f Tk_SetAppName.3 Tk_SetAppName.3.* 
    ln $S SetAppName.3$Z Tk_SetAppName.3$Z 
fi
if test -r SetCaret.3; then
    rm -f SetCaret.3.*
    $ZIP SetCaret.3
    rm -f Tk_SetCaretPos.3 Tk_SetCaretPos.3.* 
    ln $S SetCaret.3$Z Tk_SetCaretPos.3$Z 
fi
if test -r SetClass.3; then
    rm -f SetClass.3.*
    $ZIP SetClass.3
    rm -f Tk_SetClass.3 Tk_SetClass.3.* 
    rm -f Tk_Class.3 Tk_Class.3.* 
    ln $S SetClass.3$Z Tk_SetClass.3$Z 
    ln $S SetClass.3$Z Tk_Class.3$Z 
fi
if test -r SetClassProcs.3; then
    rm -f SetClassProcs.3.*
    $ZIP SetClassProcs.3
    rm -f Tk_SetClassProcs.3 Tk_SetClassProcs.3.* 
    ln $S SetClassProcs.3$Z Tk_SetClassProcs.3$Z 
fi
if test -r SetGrid.3; then
    rm -f SetGrid.3.*
    $ZIP SetGrid.3
    rm -f Tk_SetGrid.3 Tk_SetGrid.3.* 
    rm -f Tk_UnsetGrid.3 Tk_UnsetGrid.3.* 
    ln $S SetGrid.3$Z Tk_SetGrid.3$Z 
    ln $S SetGrid.3$Z Tk_UnsetGrid.3$Z 
fi
if test -r SetOptions.3; then
    rm -f SetOptions.3.*
    $ZIP SetOptions.3
    rm -f Tk_CreateOptionTable.3 Tk_CreateOptionTable.3.* 
    rm -f Tk_DeleteOptionTable.3 Tk_DeleteOptionTable.3.* 
    rm -f Tk_InitOptions.3 Tk_InitOptions.3.* 
    rm -f Tk_SetOptions.3 Tk_SetOptions.3.* 
    rm -f Tk_FreeSavedOptions.3 Tk_FreeSavedOptions.3.* 
    rm -f Tk_RestoreSavedOptions.3 Tk_RestoreSavedOptions.3.* 
    rm -f Tk_GetOptionValue.3 Tk_GetOptionValue.3.* 
    rm -f Tk_GetOptionInfo.3 Tk_GetOptionInfo.3.* 
    rm -f Tk_FreeConfigOptions.3 Tk_FreeConfigOptions.3.* 
    rm -f Tk_Offset.3 Tk_Offset.3.* 
    ln $S SetOptions.3$Z Tk_CreateOptionTable.3$Z 
    ln $S SetOptions.3$Z Tk_DeleteOptionTable.3$Z 
    ln $S SetOptions.3$Z Tk_InitOptions.3$Z 
    ln $S SetOptions.3$Z Tk_SetOptions.3$Z 
    ln $S SetOptions.3$Z Tk_FreeSavedOptions.3$Z 
    ln $S SetOptions.3$Z Tk_RestoreSavedOptions.3$Z 
    ln $S SetOptions.3$Z Tk_GetOptionValue.3$Z 
    ln $S SetOptions.3$Z Tk_GetOptionInfo.3$Z 
    ln $S SetOptions.3$Z Tk_FreeConfigOptions.3$Z 
    ln $S SetOptions.3$Z Tk_Offset.3$Z 
fi
if test -r SetVisual.3; then
    rm -f SetVisual.3.*
    $ZIP SetVisual.3
    rm -f Tk_SetWindowVisual.3 Tk_SetWindowVisual.3.* 
    ln $S SetVisual.3$Z Tk_SetWindowVisual.3$Z 
fi
if test -r StrictMotif.3; then
    rm -f StrictMotif.3.*
    $ZIP StrictMotif.3
    rm -f Tk_StrictMotif.3 Tk_StrictMotif.3.* 
    ln $S StrictMotif.3$Z Tk_StrictMotif.3$Z 
fi
if test -r TextLayout.3; then
    rm -f TextLayout.3.*
    $ZIP TextLayout.3
    rm -f Tk_ComputeTextLayout.3 Tk_ComputeTextLayout.3.* 
    rm -f Tk_FreeTextLayout.3 Tk_FreeTextLayout.3.* 
    rm -f Tk_DrawTextLayout.3 Tk_DrawTextLayout.3.* 
    rm -f Tk_UnderlineTextLayout.3 Tk_UnderlineTextLayout.3.* 
    rm -f Tk_PointToChar.3 Tk_PointToChar.3.* 
    rm -f Tk_CharBbox.3 Tk_CharBbox.3.* 
    rm -f Tk_DistanceToTextLayout.3 Tk_DistanceToTextLayout.3.* 
    rm -f Tk_IntersectTextLayout.3 Tk_IntersectTextLayout.3.* 
    rm -f Tk_TextLayoutToPostscript.3 Tk_TextLayoutToPostscript.3.* 
    ln $S TextLayout.3$Z Tk_ComputeTextLayout.3$Z 
    ln $S TextLayout.3$Z Tk_FreeTextLayout.3$Z 
    ln $S TextLayout.3$Z Tk_DrawTextLayout.3$Z 
    ln $S TextLayout.3$Z Tk_UnderlineTextLayout.3$Z 
    ln $S TextLayout.3$Z Tk_PointToChar.3$Z 
    ln $S TextLayout.3$Z Tk_CharBbox.3$Z 
    ln $S TextLayout.3$Z Tk_DistanceToTextLayout.3$Z 
    ln $S TextLayout.3$Z Tk_IntersectTextLayout.3$Z 
    ln $S TextLayout.3$Z Tk_TextLayoutToPostscript.3$Z 
fi
if test -r TkInitStubs.3; then
    rm -f TkInitStubs.3.*
    $ZIP TkInitStubs.3
    rm -f Tk_InitStubs.3 Tk_InitStubs.3.* 
    ln $S TkInitStubs.3$Z Tk_InitStubs.3$Z 
fi
if test -r Tk_Init.3; then
    rm -f Tk_Init.3.*
    $ZIP Tk_Init.3
    rm -f Tk_SafeInit.3 Tk_SafeInit.3.* 
    ln $S Tk_Init.3$Z Tk_SafeInit.3$Z 
fi
if test -r Tk_Main.3; then
    rm -f Tk_Main.3.*
    $ZIP Tk_Main.3
fi
if test -r WindowId.3; then
    rm -f WindowId.3.*
    $ZIP WindowId.3
    rm -f Tk_WindowId.3 Tk_WindowId.3.* 
    rm -f Tk_Parent.3 Tk_Parent.3.* 
    rm -f Tk_Display.3 Tk_Display.3.* 
    rm -f Tk_DisplayName.3 Tk_DisplayName.3.* 
    rm -f Tk_ScreenNumber.3 Tk_ScreenNumber.3.* 
    rm -f Tk_Screen.3 Tk_Screen.3.* 
    rm -f Tk_X.3 Tk_X.3.* 
    rm -f Tk_Y.3 Tk_Y.3.* 
    rm -f Tk_Width.3 Tk_Width.3.* 
    rm -f Tk_Height.3 Tk_Height.3.* 
    rm -f Tk_Changes.3 Tk_Changes.3.* 
    rm -f Tk_Attributes.3 Tk_Attributes.3.* 
    rm -f Tk_IsContainer.3 Tk_IsContainer.3.* 
    rm -f Tk_IsEmbedded.3 Tk_IsEmbedded.3.* 
    rm -f Tk_IsMapped.3 Tk_IsMapped.3.* 
    rm -f Tk_IsTopLevel.3 Tk_IsTopLevel.3.* 
    rm -f Tk_ReqWidth.3 Tk_ReqWidth.3.* 
    rm -f Tk_ReqHeight.3 Tk_ReqHeight.3.* 
    rm -f Tk_MinReqWidth.3 Tk_MinReqWidth.3.* 
    rm -f Tk_MinReqHeight.3 Tk_MinReqHeight.3.* 
    rm -f Tk_InternalBorderLeft.3 Tk_InternalBorderLeft.3.* 
    rm -f Tk_InternalBorderRight.3 Tk_InternalBorderRight.3.* 
    rm -f Tk_InternalBorderTop.3 Tk_InternalBorderTop.3.* 
    rm -f Tk_InternalBorderBottom.3 Tk_InternalBorderBottom.3.* 
    rm -f Tk_Visual.3 Tk_Visual.3.* 
    rm -f Tk_Depth.3 Tk_Depth.3.* 
    rm -f Tk_Colormap.3 Tk_Colormap.3.* 
    ln $S WindowId.3$Z Tk_WindowId.3$Z 
    ln $S WindowId.3$Z Tk_Parent.3$Z 
    ln $S WindowId.3$Z Tk_Display.3$Z 
    ln $S WindowId.3$Z Tk_DisplayName.3$Z 
    ln $S WindowId.3$Z Tk_ScreenNumber.3$Z 
    ln $S WindowId.3$Z Tk_Screen.3$Z 
    ln $S WindowId.3$Z Tk_X.3$Z 
    ln $S WindowId.3$Z Tk_Y.3$Z 
    ln $S WindowId.3$Z Tk_Width.3$Z 
    ln $S WindowId.3$Z Tk_Height.3$Z 
    ln $S WindowId.3$Z Tk_Changes.3$Z 
    ln $S WindowId.3$Z Tk_Attributes.3$Z 
    ln $S WindowId.3$Z Tk_IsContainer.3$Z 
    ln $S WindowId.3$Z Tk_IsEmbedded.3$Z 
    ln $S WindowId.3$Z Tk_IsMapped.3$Z 
    ln $S WindowId.3$Z Tk_IsTopLevel.3$Z 
    ln $S WindowId.3$Z Tk_ReqWidth.3$Z 
    ln $S WindowId.3$Z Tk_ReqHeight.3$Z 
    ln $S WindowId.3$Z Tk_MinReqWidth.3$Z 
    ln $S WindowId.3$Z Tk_MinReqHeight.3$Z 
    ln $S WindowId.3$Z Tk_InternalBorderLeft.3$Z 
    ln $S WindowId.3$Z Tk_InternalBorderRight.3$Z 
    ln $S WindowId.3$Z Tk_InternalBorderTop.3$Z 
    ln $S WindowId.3$Z Tk_InternalBorderBottom.3$Z 
    ln $S WindowId.3$Z Tk_Visual.3$Z 
    ln $S WindowId.3$Z Tk_Depth.3$Z 
    ln $S WindowId.3$Z Tk_Colormap.3$Z 
fi
if test -r bell.n; then
    rm -f bell.n.*
    $ZIP bell.n
fi
if test -r bind.n; then
    rm -f bind.n.*
    $ZIP bind.n
fi
if test -r bindtags.n; then
    rm -f bindtags.n.*
    $ZIP bindtags.n
fi
if test -r bitmap.n; then
    rm -f bitmap.n.*
    $ZIP bitmap.n
fi
if test -r button.n; then
    rm -f button.n.*
    $ZIP button.n
fi
if test -r canvas.n; then
    rm -f canvas.n.*
    $ZIP canvas.n
fi
if test -r checkbutton.n; then
    rm -f checkbutton.n.*
    $ZIP checkbutton.n
fi
if test -r chooseColor.n; then
    rm -f chooseColor.n.*
    $ZIP chooseColor.n
    rm -f tk_chooseColor.n tk_chooseColor.n.* 
    ln $S chooseColor.n$Z tk_chooseColor.n$Z 
fi
if test -r chooseDirectory.n; then
    rm -f chooseDirectory.n.*
    $ZIP chooseDirectory.n
    rm -f tk_chooseDirectory.n tk_chooseDirectory.n.* 
    ln $S chooseDirectory.n$Z tk_chooseDirectory.n$Z 
fi
if test -r clipboard.n; then
    rm -f clipboard.n.*
    $ZIP clipboard.n
fi
if test -r colors.n; then
    rm -f colors.n.*
    $ZIP colors.n
fi
if test -r console.n; then
    rm -f console.n.*
    $ZIP console.n
fi
if test -r cursors.n; then
    rm -f cursors.n.*
    $ZIP cursors.n
fi
if test -r destroy.n; then
    rm -f destroy.n.*
    $ZIP destroy.n
fi
if test -r dialog.n; then
    rm -f dialog.n.*
    $ZIP dialog.n
    rm -f tk_dialog.n tk_dialog.n.* 
    ln $S dialog.n$Z tk_dialog.n$Z 
fi
if test -r entry.n; then
    rm -f entry.n.*
    $ZIP entry.n
fi
if test -r event.n; then
    rm -f event.n.*
    $ZIP event.n
fi
if test -r focus.n; then
    rm -f focus.n.*
    $ZIP focus.n
fi
if test -r focusNext.n; then
    rm -f focusNext.n.*
    $ZIP focusNext.n
    rm -f tk_focusNext.n tk_focusNext.n.* 
    rm -f tk_focusPrev.n tk_focusPrev.n.* 
    rm -f tk_focusFollowsMouse.n tk_focusFollowsMouse.n.* 
    ln $S focusNext.n$Z tk_focusNext.n$Z 
    ln $S focusNext.n$Z tk_focusPrev.n$Z 
    ln $S focusNext.n$Z tk_focusFollowsMouse.n$Z 
fi
if test -r font.n; then
    rm -f font.n.*
    $ZIP font.n
fi
if test -r frame.n; then
    rm -f frame.n.*
    $ZIP frame.n
fi
if test -r getOpenFile.n; then
    rm -f getOpenFile.n.*
    $ZIP getOpenFile.n
    rm -f tk_getOpenFile.n tk_getOpenFile.n.* 
    rm -f tk_getSaveFile.n tk_getSaveFile.n.* 
    ln $S getOpenFile.n$Z tk_getOpenFile.n$Z 
    ln $S getOpenFile.n$Z tk_getSaveFile.n$Z 
fi
if test -r grab.n; then
    rm -f grab.n.*
    $ZIP grab.n
fi
if test -r grid.n; then
    rm -f grid.n.*
    $ZIP grid.n
fi
if test -r image.n; then
    rm -f image.n.*
    $ZIP image.n
fi
if test -r keysyms.n; then
    rm -f keysyms.n.*
    $ZIP keysyms.n
fi
if test -r label.n; then
    rm -f label.n.*
    $ZIP label.n
fi
if test -r labelframe.n; then
    rm -f labelframe.n.*
    $ZIP labelframe.n
fi
if test -r listbox.n; then
    rm -f listbox.n.*
    $ZIP listbox.n
fi
if test -r loadTk.n; then
    rm -f loadTk.n.*
    $ZIP loadTk.n
fi
if test -r lower.n; then
    rm -f lower.n.*
    $ZIP lower.n
fi
if test -r menu.n; then
    rm -f menu.n.*
    $ZIP menu.n
    rm -f tk_menuSetFocus.n tk_menuSetFocus.n.* 
    ln $S menu.n$Z tk_menuSetFocus.n$Z 
fi
if test -r menubar.n; then
    rm -f menubar.n.*
    $ZIP menubar.n
    rm -f tk_menuBar.n tk_menuBar.n.* 
    rm -f tk_bindForTraversal.n tk_bindForTraversal.n.* 
    ln $S menubar.n$Z tk_menuBar.n$Z 
    ln $S menubar.n$Z tk_bindForTraversal.n$Z 
fi
if test -r menubutton.n; then
    rm -f menubutton.n.*
    $ZIP menubutton.n
fi
if test -r message.n; then
    rm -f message.n.*
    $ZIP message.n
fi
if test -r messageBox.n; then
    rm -f messageBox.n.*
    $ZIP messageBox.n
    rm -f tk_messageBox.n tk_messageBox.n.* 
    ln $S messageBox.n$Z tk_messageBox.n$Z 
fi
if test -r option.n; then
    rm -f option.n.*
    $ZIP option.n
fi
if test -r optionMenu.n; then
    rm -f optionMenu.n.*
    $ZIP optionMenu.n
    rm -f tk_optionMenu.n tk_optionMenu.n.* 
    ln $S optionMenu.n$Z tk_optionMenu.n$Z 
fi
if test -r options.n; then
    rm -f options.n.*
    $ZIP options.n
fi
if test -r pack-old.n; then
    rm -f pack-old.n.*
    $ZIP pack-old.n
fi
if test -r pack.n; then
    rm -f pack.n.*
    $ZIP pack.n
fi
if test -r palette.n; then
    rm -f palette.n.*
    $ZIP palette.n
    rm -f tk_setPalette.n tk_setPalette.n.* 
    rm -f tk_bisque.n tk_bisque.n.* 
    ln $S palette.n$Z tk_setPalette.n$Z 
    ln $S palette.n$Z tk_bisque.n$Z 
fi
if test -r panedwindow.n; then
    rm -f panedwindow.n.*
    $ZIP panedwindow.n
fi
if test -r photo.n; then
    rm -f photo.n.*
    $ZIP photo.n
fi
if test -r place.n; then
    rm -f place.n.*
    $ZIP place.n
fi
if test -r popup.n; then
    rm -f popup.n.*
    $ZIP popup.n
    rm -f tk_popup.n tk_popup.n.* 
    ln $S popup.n$Z tk_popup.n$Z 
fi
if test -r radiobutton.n; then
    rm -f radiobutton.n.*
    $ZIP radiobutton.n
fi
if test -r raise.n; then
    rm -f raise.n.*
    $ZIP raise.n
fi
if test -r scale.n; then
    rm -f scale.n.*
    $ZIP scale.n
fi
if test -r scrollbar.n; then
    rm -f scrollbar.n.*
    $ZIP scrollbar.n
fi
if test -r selection.n; then
    rm -f selection.n.*
    $ZIP selection.n
fi
if test -r send.n; then
    rm -f send.n.*
    $ZIP send.n
fi
if test -r spinbox.n; then
    rm -f spinbox.n.*
    $ZIP spinbox.n
fi
if test -r text.n; then
    rm -f text.n.*
    $ZIP text.n
    rm -f tk_textCopy.n tk_textCopy.n.* 
    rm -f tk_textCut.n tk_textCut.n.* 
    rm -f tk_textPaste.n tk_textPaste.n.* 
    ln $S text.n$Z tk_textCopy.n$Z 
    ln $S text.n$Z tk_textCut.n$Z 
    ln $S text.n$Z tk_textPaste.n$Z 
fi
if test -r tk.n; then
    rm -f tk.n.*
    $ZIP tk.n
fi
if test -r tkerror.n; then
    rm -f tkerror.n.*
    $ZIP tkerror.n
fi
if test -r tkvars.n; then
    rm -f tkvars.n.*
    $ZIP tkvars.n
fi
if test -r tkwait.n; then
    rm -f tkwait.n.*
    $ZIP tkwait.n
fi
if test -r toplevel.n; then
    rm -f toplevel.n.*
    $ZIP toplevel.n
fi
if test -r winfo.n; then
    rm -f winfo.n.*
    $ZIP winfo.n
fi
if test -r wish.1; then
    rm -f wish.1.*
    $ZIP wish.1
fi
if test -r wm.n; then
    rm -f wm.n.*
    $ZIP wm.n
fi
exit 0
