vtk_module(vtkPVClientServerCoreDefault
  DEPENDS
    vtkPVClientServerCoreRendering
    vtkPVVTKExtensionsDefault
  PRIVATE_DEPENDS
    vtksys
  TEST_DEPENDS
    vtkTestingCore
  TEST_LABELS
    PARAVIEW
)
