NAME
  ParaView::ClientServerCoreDefault
LIBRARY_NAME
  vtkPVClientServerCoreDefault
KIT
  ParaView::ClientServerKit
DEPENDS
  ParaView::ClientServerCoreRendering
  ParaView::VTKExtensionsDefault

  # Only needed because of the vtkPythonInterpreter optional dependency.
  VTK::FiltersProgrammable
PRIVATE_DEPENDS
  VTK::IOInfovis
  VTK::vtksys
TEST_DEPENDS
  VTK::TestingCore
TEST_OPTIONAL_DEPENDS
  VTK::ParallelMPI
  VTK::Python

  # This is due to a public optional dependency in
  # ParaView::VTKExtensionsRendering.
  ParaView::icet
TEST_LABELS
  ParaView
