NAME
  LANLX3DReader::vtkLANLX3DReader
LIBRARY_NAME
  vtkLANLX3DReader
SPDX_LICENSE_IDENTIFIER
  LicenseRef-BSD-3-Clause-LANL-Triad-USGov
SPDX_COPYRIGHT_TEXT
  Copyright (c) Kitware Inc.
  Copyright (c) 2021, Los Alamos National Laboratory
  Copyright © 2021. Triad National Security, LLC. All rights reserved.
SPDX_CUSTOM_LICENSE_FILE
  LICENSE
SPDX_CUSTOM_LICENSE_NAME
  BSD-3-Clause-LANL-Triad-USGov
LICENSE_FILES
  LICENSE
DEPENDS
  VTK::FiltersCore
PRIVATE_DEPENDS
  VTK::CommonCore
