vtk_module(pqApplicationComponents
  GROUPS
    ParaViewQt
  DEPENDS
    pqComponents
    vtkGUISupportQt
  PRIVATE_DEPENDS
    vtkPVAnimation
    vtkPVServerManagerDefault
    vtkPVServerManagerRendering
    vtksys
  EXCLUDE_FROM_WRAPPING
  TEST_LABELS
    PARAVIEW
)
