vtk_module(vtkPointSpriteRendering
  DEPENDS
    vtkFiltersHybrid
    vtkRenderingOpenGL
    vtkImagingCore
    vtkInteractionStyle
    vtkRenderingFreeType
  COMPILE_DEPENDS
    vtkUtilitiesEncodeString
  EXCLUDE_FROM_WRAP_HIERARCHY
  TEST_LABELS
    PARAVIEW
)
