# module for kwwidgets

import os

if os.name == 'posix':
    from libKWWidgetsPython import *
else:
    from KWWidgetsPython import *

icons = {
    "IconNoIcon"                    : 0,
    "IconAngleTool"                 : 14,
    "IconBoundingBox"               : 13,
    "IconCamera"                    : 19,
    "IconColorBarAnnotation"        : 12,
    "IconColorSquares"              : 18,
    "IconConnection"                : 1,
    "IconContourTool"               : 16,
    "IconContourSegment"            : 33,
    "IconCornerAnnotation"          : 11,
    "IconCropTool"                  : 22,
    "IconDistanceTool"              : 15,
    "IconDocument"                  : 9,
    "IconEmpty16x16"                : 6,
    "IconEmpty1x1"                  : 10,
    "IconError"                     : 2, 
    "IconErrorMini"                 : 3,
    "IconErrorRedMini"              : 4,
    "IconExpand"                    : 5,
    "IconEye"                       : 17,
    "IconFileOpen"                  : 8,
    "IconFloppy"                    : 7,
    "IconFolder"                    : 20,
    "IconFolderOpen"                : 21,
    "IconGridLinear"                : 40,
    "IconGridLog"                   : 41,
    "IconHeaderAnnotation"          : 50,
    "IconHelpBubble"                : 60,
    "IconInfoMini"                  : 61,
    "IconLock"                      : 62,
    "IconMagGlass"                  : 63,
    "IconMinus"                     : 64,
    "IconMove"                      : 80,
    "IconMoveH"                     : 81,
    "IconMoveV"                     : 82,
    "IconOrientationCubeAnnotation" : 83,
    "IconPanHand"                   : 84,
    "IconPlus"                      : 100,
    "IconPointFinger"               : 90,
    "IconPresetAdd"                 : 94,
    "IconPresetApply"               : 95,
    "IconPresetDelete"              : 96,
    "IconPresetEmail"               : 97,
    "IconPresetLocate"              : 98,
    "IconPresetUpdate"              : 99,
    "IconQuestion"                  : 101,
    "IconReload"                    : 102,
    "IconRotate"                    : 105,
    "IconScaleBarAnnotation"        : 106,
    "IconSideAnnotation"            : 110,
    "IconSpinDown"                  : 111,
    "IconSpinLeft"                  : 112,
    "IconSpinRight"                 : 113,
    "IconSpinUp"                    : 114,
    "IconShrink"                    : 103,
    "IconStopwatch"                 : 104,
    "IconTransportBeginning"        : 120,
    "IconTransportEnd"              : 121,
    "IconTransportFastForward"      : 122,
    "IconTransportFastForwardToKey" : 123,
    "IconTransportLoop"             : 124,
    "IconTransportPause"            : 125,
    "IconTransportPlay"             : 126,
    "IconTransportPlayToKey"        : 127,
    "IconTransportRewind"           : 128,
    "IconTransportRewindToKey"      : 129,
    "IconTransportStop"             : 130,
    "IconTrashcan"                  : 131,
    "IconTreeClose"                 : 150,
    "IconTreeOpen"                  : 151,
    "IconWarning"                   : 170,
    "IconWarningMini"               : 171,
    "IconWindowLevel"               : 172,
    }

for key, val in icons.items():
    vtkKWIcon.__dict__[key] = val

del icons
