NAME
  ParaView::VTKExtensionsExtraction
LIBRARY_NAME
  vtkPVVTKExtensionsExtraction
SPDX_LICENSE_IDENTIFIER
  BSD-3-Clause
SPDX_COPYRIGHT_TEXT
  Copyright (c) Kitware Inc.
DESCRIPTION
  Extraction filters
GROUPS
  PARAVIEW_CORE
KIT
  ParaView::CoreKit
DEPENDS
  VTK::FiltersExtraction
  VTK::FiltersSources
PRIVATE_DEPENDS
  VTK::ParallelCore
OPTIONAL_DEPENDS
  ParaView::VTKExtensionsExtractionPython
TEST_LABELS
  ParaView
