'\"
'\" Copyright (c) 1998-2000 by Scriptics Corporation.
'\" All rights reserved.
'\" 
'\" RCS: @(#) Id
'\" 
'\"
.so man.macros
.TH Tk_GetHWND 3 "" Tk "Tk Library Procedures"
.BS
.SH NAME
Tk_GetHWND \- retrieve the Windows handle for an X window
.SH SYNOPSIS
.nf
\fB#include <tk.h>\fR
.sp
HWND
\fBTk_GetHWND\fR(\fIwindow\fR)
.SH ARGUMENTS
.AP Window window in
X token for window.
.BE
.SH DESCRIPTION
.PP
\fBTk_GetHWND\fR returns the Windows HWND identifier for X Windows
window given by \fIwindow\fR.

.SH KEYWORDS
identifier, window
