NAME
  GenericIOReader::vtkGenericIOReader
LIBRARY_NAME
  vtkGenericIOReader
SPDX_LICENSE_IDENTIFIER
  LicenseRef-BSD-3-Clause-LANL-USGov
SPDX_COPYRIGHT_TEXT
  Copyright (c) Kitware, Inc.
  Copyright 2017. Los Alamos National Security, LLC.
  Copyright (C) 2015, UChicago Argonne, LLC
SPDX_CUSTOM_LICENSE_FILE
  LICENSE
SPDX_CUSTOM_LICENSE_NAME
  BSD-3-Clause-LANL-USGov
LICENSE_FILES
  LICENSE
DEPENDS
  VTK::CommonCore
  VTK::CommonDataModel
  VTK::CommonExecutionModel
  VTK::ParallelCore
  VTK::ParallelMPI
