set(PARAVIEW_BUILD_EXAMPLES ON CACHE BOOL "")

# External package settings.
set(PARAVIEW_BUILD_WITH_EXTERNAL ON CACHE BOOL "")
set(VTK_MODULE_USE_EXTERNAL_VTK_libharu OFF CACHE BOOL "")
set(VTK_MODULE_USE_EXTERNAL_ParaView_cgns OFF CACHE BOOL "")
set(VTK_MODULE_USE_EXTERNAL_VTK_gl2ps OFF CACHE BOOL "")

include("${CMAKE_CURRENT_LIST_DIR}/configure_fedora33.cmake")
