set(PARAVIEW_PLUGIN_ENABLE_pvNVIDIAIndeX ON CACHE BOOL "")
set(PARAVIEW_PLUGIN_ENABLE_zSpace ON CACHE BOOL "")
set(PARAVIEW_PLUGIN_ENABLE_XRInterface ON CACHE BOOL "")

include("${CMAKE_CURRENT_LIST_DIR}/configure_common.cmake")
