# Lines can be generated by doing:
#
#   sha256sum $files | awk '{ print "set(\"" $2 "_hash\" " $1 ")" }' >> $thisfile

set("5.15.2-0-202011130602qtbase-Windows-Windows_10-MSVC2015-Windows-Windows_10-X86_64.7z_hash" 7d06f93329b79de466aba37109c2aa850ddd74ac03a054b545aeff272a716851)
set("5.15.2-0-202011130602qtsvg-Windows-Windows_10-MSVC2015-Windows-Windows_10-X86_64.7z_hash" af204df1e149a862a9f9b2ebe9542a913275a2b3c54435857dd0c42b18ce5e0d)
set("5.15.2-0-202011130602qttools-Windows-Windows_10-MSVC2015-Windows-Windows_10-X86_64.7z_hash" 210ad3e88ffbc2bda58371a227f0dcbb06719bd5acbd19d44e7da4f5b2d2af4b)
set("5.15.2-0-202011130602qtxmlpatterns-Windows-Windows_10-MSVC2015-Windows-Windows_10-X86_64.7z_hash" f6ae775677ce96a28ab6df8e6cee138e9fcb69e45e4d6485b6d8a26e1de857dc)

# There's a filename conflict here.
if (msvc_year STREQUAL "2019")
  set("5.15.2-0-202011130602d3dcompiler_47-x64.7z_hash" 0dc63ca9bb91cb204d479356edb89b30e3599f1c0bce469b1dd5a339134f25e2)
  set("5.15.2-0-202011130602opengl32sw-64-mesa_12_0_rc2.7z_hash" 4e43bc46665f31e12e528f01105310b07d3b8c0ff914668e3b77969d672fcc14)
elseif (msvc_year STREQUAL "2015")
  set("5.15.2-0-202011130602d3dcompiler_47-x64.7z_hash" 9ba5998b18974f43c8bad4e9ba1fbef0642dcb40ede2f3c7d01d4634f6296f1a)
  set("5.15.2-0-202011130602opengl32sw-64-mesa_12_0_rc2.7z_hash" d4f11612346a0e2c23e2752f27f440c33adc42405faae7b7eb49bef74e33f2f7)
endif ()
set("5.15.2-0-202011130602qtbase-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z_hash" e563de40230295841c2eece26e347de709edc4bf035515cc239cae3c994c9af6)
set("5.15.2-0-202011130602qtsvg-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z_hash" 22daa63531f2eed8aeec02e047b73641739fa9d0288a5d2db4da25baf3a005a7)
set("5.15.2-0-202011130602qttools-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z_hash" babb583bbbac0e946ad25a2a687b4a3349779d750b1f3de1c4dadbf1c343c3ea)
set("5.15.2-0-202011130602qtxmlpatterns-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z_hash" cc295d93f74c38277cb5fa2c56cbc1dfd8594a5228a82000c901fe42332e1c69)

set("5.15.2-0-202011130601qtbase-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z_hash" a6b225c8ae4eed1b5de1109b27c9c85ea779f56cdeea44ec48d136f32370c6e3)
set("5.15.2-0-202011130601qtsvg-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z_hash" 94f1c25eba441c97870597140c9b5db7e8b6d75865875be6ceca929ebd44c2f8)
set("5.15.2-0-202011130601qttools-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z_hash" 96f46f690845184ea5a99010c7b59e14443ca0fa4b91f0ea37a2d25af1a3de55)
set("5.15.2-0-202011130601qtxmlpatterns-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z_hash" 1a98346e84937f9e87d0b5375a90e18f70568b880bc70b141dc7f3cafac8c154)

set("6.5.0-0-202303161324qtbase-MacOS-MacOS_12-Clang-MacOS-MacOS_12-X86_64-ARM64.7z_hash" e06f7a44ec7dc45af409ef31980b553a97c7bd40e7a081fa7f7cde7ec1d66d8e)
set("6.5.0-0-202303161324qtsvg-MacOS-MacOS_12-Clang-MacOS-MacOS_12-X86_64-ARM64.7z_hash" c15fda223e1f479514119d7b5e40db896c43dc6ee6e020f91900697aa5ecc732)
set("6.5.0-0-202303161324qttools-MacOS-MacOS_12-Clang-MacOS-MacOS_12-X86_64-ARM64.7z_hash" 16a0a229ce48cd9e9e07b19062bc9907bc2684436a3ad1234031d078365aa921)
set("6.5.0-0-202303161324qttranslations-MacOS-MacOS_12-Clang-MacOS-MacOS_12-X86_64-ARM64.7z_hash" 437783112eab9e614c56ec89abb4c0078a6e41900a83a8b29909073a93b86f64)
set("6.5.0-0-202303290841qt5compat-MacOS-MacOS_12-Clang-MacOS-MacOS_12-X86_64-ARM64.7z_hash" 0362214b94b81f25dd0f384c6fe2230d6931722d4d5ec0bac8757bcd7c283d1e)

set("6.5.0-0-202303161324d3dcompiler_47-x64.7z_hash" cb57f81bbd66f149ce7b6bc3017ce86a7e1dfd5a9155ed13ab2ef9b20b97e50c)
set("6.5.0-0-202303161324opengl32sw-64-mesa_11_2_2-signed.7z_hash" 51fccfc8cbbf91fad56cc0803dbdab9d0684de42af031a73ae372dcf037281c1)
set("6.5.0-0-202303161324qtbase-Windows-Windows_10_22H2-MSVC2019-Windows-Windows_10_22H2-X86_64.7z_hash" 99efea6cac1495c463c0e5dfb4fdf0217bee9d9179287e950901776756b09f09)
set("6.5.0-0-202303161324qtsvg-Windows-Windows_10_22H2-MSVC2019-Windows-Windows_10_22H2-X86_64.7z_hash" 785917172410e4e35e872ab159899f6728a993f8cf9d2f193dee6226ef158227)
set("6.5.0-0-202303161324qttools-Windows-Windows_10_22H2-MSVC2019-Windows-Windows_10_22H2-X86_64.7z_hash" 5a5e3f2277459c6d1c168c1593bc806b8bc0d3c5d9e7dff4a9fb7f9e204b7077)
set("6.5.0-0-202303161324qttranslations-Windows-Windows_10_22H2-MSVC2019-Windows-Windows_10_22H2-X86_64.7z_hash" 9b659db9aecbff475907abd7bd613bfebfca9ad9442c16522152ddd474da7c6f)
set("6.5.0-0-202303290841qt5compat-Windows-Windows_10_22H2-MSVC2019-Windows-Windows_10_22H2-X86_64.7z_hash" 959c8b1d6bb5f5b500a15433e8734810b1eb4fbd90f63270a5a27173aede4a2f)
