list(APPEND Module_SRCS
vtkAppendCompositeDataLeaves.cxx
vtkAppendFilter.cxx
vtkAppendPolyData.cxx
vtkCellDataToPointData.cxx
vtkFeatureEdges.cxx
vtkImageAppend.cxx
vtkPointDataToCellData.cxx
vtkProbeFilter.cxx
vtkQuadricClustering.cxx
vtkThreshold.cxx
)
